### ISSUE TITLE
Support for @Validated on @ConfigurationProperties

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#142]
Hi,

i used in my test project @ConfigurationProperties . I validate them with @Validated which works fine on a normal JVM.

As I know in native-image CGLIBProxy isn't supported which result into this error:

```
May 25, 2020 10:56:33 AM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keycloakConfigProperties' defined in class path resource [de/adorsys/keycloak/config/properties/KeycloakConfigProperties.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:27)
Caused by: org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images
	at org.springframework.aop.framework.DefaultAopProxyFactory.createAopProxy(DefaultAopProxyFactory.java:26)
	at org.springframework.aop.framework.ProxyCreatorSupport.createAopProxy(ProxyCreatorSupport.java:105)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.postProcessAfterInitialization(AbstractAdvisingBeanPostProcessor.java:92)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	... 15 more
```

Is this a wrong default setting in spring or it's possible to use Validated without cglibproxy?

**Comment by jkroepke** [comment]
Is there an update with spring 2.4.0 and 0.8.0?

**Comment by jkroepke** [comment]
If I add some manual configuration, validation may work. (getting errors). But provide all properties correctly raises an error above.

Here what I do:

Add to proxy-config.json:
```  
["javax.validation.Validator","org.springframework.aop.SpringProxy","org.springframework.aop.framework.Advised","org.springframework.core.DecoratingProxy"],
```
Add to reflect-config.json:
```
  {
    "name": "org.springframework.boot.context.properties.ConstructorBinding",
    "allDeclaredMethods": true
  },
  {
    "name":"org.springframework.boot.context.properties.ConfigurationPropertiesBinder",
    "allDeclaredMethods":true
  },
  {
    "name":"org.springframework.boot.context.properties.ConfigurationPropertiesBinder$Factory",
    "allDeclaredMethods":true
  },
  {
    "name":"org.springframework.boot.context.properties.ConstructorBinding",
    "allDeclaredMethods":true
  },
  {
    "name":"org.springframework.boot.context.properties.EnableConfigurationProperties",
    "allDeclaredMethods":true
  },
  {
    "name":"org.springframework.boot.context.properties.EnableConfigurationPropertiesRegistrar",
    "allDeclaredConstructors":true
  },


  {
    "name": "javax.validation.Constraint",
    "allDeclaredMethods": true
  },
  {
    "name": "javax.validation.ConstraintValidator",
    "allPublicMethods": true,
    "methods": [
      {
        "name": "initialize",
        "parameterTypes": [
          "java.lang.annotation.Annotation"
        ]
      }
    ]
  },
  {
    "name": "javax.validation.Validator",
    "allDeclaredMethods": true
  },
  {
    "name": "javax.validation.ValidatorFactory"
  },
  {
    "name": "javax.validation.bootstrap.GenericBootstrap"
  },
  {
    "name": "javax.validation.constraints.NotBlank",
    "allDeclaredMethods": true
  },
  {
    "name": "javax.validation.constraints.NotNull",
    "allDeclaredMethods": true
  },
  {
    "name": "javax.validation.constraints.Pattern",
    "allDeclaredMethods": true
  },
  {
    "name": "javax.validation.executable.ExecutableValidator"
  },
  {
    "name": "org.springframework.validation.SmartValidator",
    "allPublicMethods": true
  },
  {
    "name": "org.springframework.validation.annotation.Validated",
    "allDeclaredMethods": true,
    "methods": [
      {
        "name": "value",
        "parameterTypes": []
      }
    ]
  },
  {
    "name": "org.springframework.validation.beanvalidation.LocalValidatorFactoryBean",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "methods": [
      {
        "name": "unwrap",
        "parameterTypes": [
          "java.lang.Class"
        ]
      }
    ]
  },
  {
    "name": "org.springframework.validation.beanvalidation.MethodValidationPostProcessor",
    "allDeclaredFields": true,
    "allDeclaredMethods": true
  },
  {
    "name": "org.springframework.validation.beanvalidation.SpringValidatorAdapter",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "methods": [
      {
        "name": "forExecutables",
        "parameterTypes": []
      },
      {
        "name": "getConstraintsForClass",
        "parameterTypes": [
          "java.lang.Class"
        ]
      },
      {
        "name": "supports",
        "parameterTypes": [
          "java.lang.Class"
        ]
      },
      {
        "name": "validate",
        "parameterTypes": [
          "java.lang.Object",
          "org.springframework.validation.Errors"
        ]
      },
      {
        "name": "validate",
        "parameterTypes": [
          "java.lang.Object",
          "org.springframework.validation.Errors",
          "java.lang.Object[]"
        ]
      },
      {
        "name": "validate",
        "parameterTypes": [
          "java.lang.Object",
          "java.lang.Class[]"
        ]
      },
      {
        "name": "validateProperty",
        "parameterTypes": [
          "java.lang.Object",
          "java.lang.String",
          "java.lang.Class[]"
        ]
      },
      {
        "name": "validateValue",
        "parameterTypes": [
          "java.lang.Class",
          "java.lang.String",
          "java.lang.Object",
          "org.springframework.validation.Errors",
          "java.lang.Object[]"
        ]
      },
      {
        "name": "validateValue",
        "parameterTypes": [
          "java.lang.Class",
          "java.lang.String",
          "java.lang.Object",
          "java.lang.Class[]"
        ]
      }
    ]
  },
  {
    "name": "org.hibernate.validator.internal.constraintvalidators.bv.NotBlankValidator",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "org.hibernate.validator.internal.constraintvalidators.bv.NotNullValidator",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  },
  {
    "name": "org.hibernate.validator.internal.constraintvalidators.bv.PatternValidator",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true,
    "methods": [
      {
        "name": "initialize",
        "parameterTypes": [
          "java.lang.annotation.Annotation"
        ]
      }
    ]
  },
```
Add to resource-config.json:
```
{
  "bundles":[{"name":"org.hibernate.validator.ValidationMessages"}]
}
```

**Comment by dsyer** [comment]
I don't think we can ever support `@Validated` like in Spring Framework on any arbitrary bean (or if we did it would only be for classes that are JDK proxyable). It would be better to be explicit about it. Spring Boot uses the same annotation though for marking `@ConfigurationProperties` beans. What is your use case exactly?

**Comment by jkroepke** [comment]
> What is your use case exactly?

Validation on `@ConfigurationProperties`.

See: https://github.com/adorsys/keycloak-config-cli/blob/5832c0aa44a3eda3fa1fda02e41d21ae51ae986f/src/main/java/de/adorsys/keycloak/config/properties/KeycloakConfigProperties.java#L34

**Comment by dsyer** [comment]
OK. We can probably work towards support for that specific use case.

**Comment by dsyer** [comment]
You can work around it for now by disabling the proxy generation. In case that helps:

```java
	@Bean
	public static BeanDefinitionRegistryPostProcessor ripper() {
		return new BeanDefinitionRegistryPostProcessor() {

			@Override
			public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
			}

			@Override
			public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry) throws BeansException {
				if (registry.containsBeanDefinition("methodValidationPostProcessor")) {
					registry.removeBeanDefinition("methodValidationPostProcessor");
				}
			}

		};
	}
```

**Comment by jkroepke** [comment]
All right, but this disables the validation, too?

**Comment by dsyer** [comment]
Well, it only disables the Spring Core feature that checks all method invocations on `@Validated` beans. Spring Boot doesn't need that. That's why I asked about your use case. You will also need some reflection configuration for the validator types that you use in your `@ConfigurationProperties` beans. I'll make a sample and push it into this repo so you can see.

**Comment by dsyer** [comment]
See https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/validator

**Comment by jkroepke** [comment]
Thanks a lot. I had to add 

https://github.com/spring-projects-experimental/spring-graalvm-native/blob/30332553840ecebc0a9bc9554cd12b626c6448e5/spring-graalvm-native-samples/validator/src/main/resources/META-INF/native-image/reflect-config.json#L8-L14

to my reflect-config.json. After that everything works as expected. 👍

**Comment by aclement** [comment]
I've automated the manual configuration that was in @dsyer validation sample. It now has no manual config. I also reworked the app a little and the `verify.sh` script so it checks validation is not just passing because it isn't happening. (I hope I've attached ValidatorFactory/GenericBootstrap to the right auto configuration trigger, but it does work for this app).

**Comment by snicoll** [comment]
For the record, the creation of the proxy when you combine `@Validated` and `@ConfigurationProperties` is done at the Spring Boot level with the default auto-configuration. Spring Boot 2.4 has been changed to not create a proxy in such a case, see https://github.com/spring-projects/spring-boot/issues/21454. 

Would it be worth trying this again with Spring Boot `2.4.0-RC1` or later. @jkroepke would you be able to give that version a try please?

**Comment by jkroepke** [comment]
Here is my branch: https://github.com/adorsys/keycloak-config-cli/pull/182

Looks good to me. Validation is working.
