### ISSUE TITLE
Trouble SpringBoot + Gradle 5 + MySQL driver + HikariCP JDBC connection pool

### ISSUE THREAD

**Issue by jbiancot** [spring-projects-experimental/spring-graalvm-native#148]
Hi... I am trying GraalVM and this basic code. I have added the MySQL driver. I am using the HikariCP JDBC connection pool.

The source code if available:

https://yisu.net/GraalVM.tgz

**Comment by aclement** [comment]
Hey. What error do you get? At image build time? At image run time? I don't see any bash scripts in there to build the native-image or native-image invocation calls in the gradle, what is the native-image command line you are using to build the image?

**Comment by jbiancot** [comment]
```
Hi,

I am getting this:


[root@debian10ForMatrix (192.168.9.9) ~/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122]  ./build.sh 
=== Building web-issue122 sample ===
Packaging web-issue122 with Maven

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 703ms
3 actionable tasks: 3 up-to-date
Unpacking web-issue122-1.0.jar
Compiling web-issue122 with GraalVM Version 20.1.0-dev (Java Version 1.8.0_252)
Apply jar:file:///root/spring-graal-nativeMay12/spring-graal-native/target/spring-graal-native-0.7.0.BUILD-SNAPSHOT.jar!/META-INF/native-image/org.springframework.experimental/spring-graal-native/native-image.properties
Executing [
/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx3310229912 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.1.0-dev \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal.jar \
-javaagent:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar=traceInitialization \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dsun.rmi.transport.tcp.maxConnectionThreads=0 \
-Dspring.graal.remove-unused-autoconfig=true \
-Dspring.graal.remove-yaml-support=true \
-Xbootclasspath/a:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/boot/graaljs-scriptengine.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/boot/graal-sdk.jar \
-cp \
/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/javacpp-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/svm-llvm.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/pointsto.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/objectfile.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/jvmci-hotspot.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal-management.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/jvmci-api.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
1804 \
-imagecp \
/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/boot/graaljs-scriptengine.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/boot/graal-sdk.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/javacpp-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/svm.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/svm-llvm.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/pointsto.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/objectfile.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/jvmci-hotspot.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/graal-management.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/jvmci/jvmci-api.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/resources.jar:/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/library-support.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/classes:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-tx-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-jdbc-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-collections-3.2.2.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-datatype-jsr310-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-tomcat-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/json-20171018.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-webmvc-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/httpcore-4.4.9.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/tomcat-embed-core-9.0.34.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/logback-classic-1.2.3.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-validator-1.6.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/mysql-connector-java-8.0.20.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-jcl-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/log4j-to-slf4j-2.13.2.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/tomcat-embed-websocket-9.0.34.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-module-parameter-names-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/snakeyaml-1.26.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/httpmime-4.5.5.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/log4j-api-2.13.2.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jakarta.annotation-api-1.3.5.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/httpclient-4.5.5.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/logback-core-1.2.3.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jul-to-slf4j-1.7.30.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-databind-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-aop-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-core-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-annotations-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jackson-datatype-jdk8-2.11.0.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/jakarta.el-3.0.3.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-beans-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-json-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-logging-1.2.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-jdbc-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/HikariCP-3.4.1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-beanutils-1.9.2.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-expression-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-codec-1.11.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/commons-digester-1.8.1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/slf4j-api-1.7.30.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-web-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-starter-logging-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-autoconfigure-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-boot-devtools-2.3.0.RC1.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-context-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-core-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image/BOOT-INF/lib/spring-web-5.2.6.RELEASE.jar:/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image:/root/spring-graal-nativeMay12/spring-graal-native/target/spring-graal-native-0.7.0.BUILD-SNAPSHOT.jar \
-H:Path=/root/spring-graal-nativeMay12/spring-graal-native-samples/web-issue122/target/native-image \
-H:EnableURLProtocols=http,jar \
-H:+TraceClassInitialization \
-H:Name=web-issue122 \
-H:+ReportExceptionStackTraces \
-H:FallbackThreshold=0 \
-H:+AllowIncompleteClasspath \
-H:+ReportUnsupportedElementsAtRuntime \
-H:CLibraryPath=/usr/lib/jvm/graalvm-ce-java8-20.1.0-dev/jre/lib/svm/clibraries/linux-amd64 \
-H:Class=net.yisu.Application \

]
[web-issue122:1823]    classlist:   6,678.99 ms,  2.02 GB
 ____             _               _____          _                  
/ ___| _ __  _ __(_)_ __   __ _  |  ___|__  __ _| |_ _   _ _ __ ___ 
\___ \| '_ \| '__| | '_ \ / _` | | |_ / _ \/ _` | __| | | | '__/ _ \
 ___) | |_) | |  | | | | | (_| | |  _|  __/ (_| | |_| |_| | | |  __/
|____/| .__/|_|  |_|_| |_|\__, | |_|  \___|\__,_|\__|\__,_|_|  \___|
      |_|                 |___/                                     

Feature operating in FEATURE mode
Removing unused configurations
Skipping Yaml support
Use -Dspring.graal.verbose=true on native-image call to see more detailed information from the feature
[web-issue122:1823]        (cap):     676.60 ms,  2.02 GB
Found #5 types in static reflection list to register
Skipping #5 types not on the classpath
Attempting proxy registration of #9 proxies
Skipped registration of #6 proxies - relevant types not on classpath
The URL protocol jar is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
[web-issue122:1823]        setup:   1,619.28 ms,  2.02 GB
Registering resources - #34 patterns
Registering resources - #2 bundles
Processing META-INF/spring.factories files...
spring.factories processing, problem adding access for key org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer: javax/validation/ValidationException
Processing spring.factories - PropertySourceLoader lists #1 property source loaders
Processing spring.factories - EnableAutoConfiguration lists #126 configurations
Excluding 95 auto-configurations from spring.factories file
Processing spring.factories - EnableAutoConfiguration lists #3 configurations
Excluding 0 auto-configurations from spring.factories file
Found no META-INF/spring.components -> synthesizing one...
Computed spring.components is 
vvv
net.yisu.RequestFilter=org.springframework.stereotype.Component
net.yisu.Application=org.springframework.stereotype.Component
net.yisu.controller.Basic=org.springframework.stereotype.Component
net.yisu.model.Configurator=org.springframework.stereotype.Component
^^^
Registered 4 entries
Configuring initialization time for specific types and packages:
#70 buildtime-init-classes   #23 buildtime-init-packages   #33 runtime-init-classes    #0 runtime-init-packages

Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.
Number of types dynamically registered for reflective access: #2804
[web-issue122:1823]     analysis:  13,531.65 ms,  2.25 GB
Error: Classes that should be initialized at run time got initialized during image building:
 com.mysql.cj.jdbc.Driver was unintentionally initialized at build time. java.sql.DriverManager caused initialization of this class with the following trace: 
	at com.mysql.cj.jdbc.Driver.<clinit>(Driver.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)

com.mysql.cj.jdbc.NonRegisteringDriver was unintentionally initialized at build time. java.sql.DriverManager caused initialization of this class with the following trace: 
	at com.mysql.cj.jdbc.NonRegisteringDriver.<clinit>(NonRegisteringDriver.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.mysql.cj.jdbc.Driver was unintentionally initialized at build time. java.sql.DriverManager caused initialization of this class with the following trace: 
	at com.mysql.cj.jdbc.Driver.<clinit>(Driver.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)

com.mysql.cj.jdbc.NonRegisteringDriver was unintentionally initialized at build time. java.sql.DriverManager caused initialization of this class with the following trace: 
	at com.mysql.cj.jdbc.NonRegisteringDriver.<clinit>(NonRegisteringDriver.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)


	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:511)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

real	0m32.216s
user	1m12.807s
sys	0m3.125s
FAILURE: an error occurred when compiling the native-image.


```

**Comment by jbiancot** [comment]
@aclement any news on this?
I'll highly appreciate it.

**Comment by sdeleuze** [comment]
I am working on that.

**Comment by jbiancot** [comment]
@sdeleuze hi, having good luck with this? or waiting to "mercury in retrograde" to finish, LoL

**Comment by jbiancot** [comment]
@sdeleuze Any sample code in order to have a basic API + Gradle + MySQL + HikariCP ?

**Comment by sdeleuze** [comment]
With Gradle nope with Maven we have https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/spring-petclinic-jdbc.

**Comment by jbiancot** [comment]
Unfortunately that won’t work for me :-/
