### ISSUE TITLE
NoClassDefFoundError for reactive RequestMappingInfoHandlerMapping

### ISSUE THREAD

**Issue by simonDeHero** [spring-projects-experimental/spring-graalvm-native#150]
Hi!
i am not sure, whether to post my issue here or in https://github.com/oracle/graal/issues but i try here (first) because it is Spring related. i try to build my app and after the analysis phase i get an error, that the reactive RequestMappingInfoHandlerMapping cannot be found. Weird thing is, that my app does not use flux or any reactive Spring library. Even when i try to find this RequestMappingInfoHandlerMapping in Intellij, i only find the mvc ones. The error still occurs, even if i delay initialization to runtime.
So how does the compile process think this class should exist :-)

the error:
```
Fatal error:java.lang.NoClassDefFoundError: org/springframework/web/reactive/result/method/RequestMappingInfoHandlerMapping
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.getEnclosingClass(Class.java:1517)
	at java.base/sun.reflect.annotation.AnnotatedTypeFactory.nestingForType(AnnotatedTypeFactory.java:96)
	at java.base/sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
	at java.base/java.lang.reflect.Executable.getAnnotatedReceiverType(Executable.java:676)
	at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedReceiverTypeComputer.compute(Target_java_lang_reflect_Executable.java:145)
	at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:269)
	at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:182)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:379)
	at com.oracle.graal.pointsto.ObjectScanner.access$500(ObjectScanner.java:61)
	at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:450)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)
```

i use:
- Spring Boot 2.3.0 RELEASE
- according starters and libraries for mvc, jpa, feign, actuator, aws sqs, micrometer, liquibase
- spring-graal-native 0.7.0 BUILD-SNAPSHOT
- GraalVM CE for java 11 version 20.1.0

my compile.sh is basically:
```
time $NATIVE_IMAGE_CMD \
  --verbose \
  --no-server -J-Xmx30G\
  --no-fallback \
  --initialize-at-build-time \
  --enable-all-security-services \
  --delay-class-initialization-to-runtime=org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping \
  -H:+TraceClassInitialization \
  -H:Name=opa \
  -H:+ReportExceptionStackTraces \
  -H:+PrintAnalysisStatistics \
  -Dspring.graal.remove-unused-autoconfig=true \
  -Dspring.graal.missing-selector-hints=warning \
  -Dspring.graal.verbose=true \
  -cp <my class path> <my Main class>
```

thx for looking into this!

**Comment by sdeleuze** [comment]
Hey, not sure yet what is the issue but beware you should use `-Dspring.native.` with 0.7.0 snapshot builds not `-Dspring.graal.`.

**Comment by simonDeHero** [comment]
@sdeleuze thx for having a look! 
switching to `-Dspring.graal.` seemed to have helped in the described error. now i got a new one :-)

so we can close this issue, and i will investigate my new error and maybe create another issue.

thx again and bye!
