### ISSUE TITLE
How can we avoid the need to exclude netty-transport-native-epoll from webflux on linux?

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-graalvm-native#153]
The need to do this for all netty cases (on linux) is a problem. What is a better way?
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport-native-epoll</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Is there a flag to change netty behaviour or some other way to avoid it getting processed?

**Comment by aclement** [comment]
(I believe it is a sticking point for just grabbing something webfluxy from start.spring.io and deploying to linux). Not sure we talk about this in the docs either, should be in troubleshooting for 0.7

**Comment by aclement** [comment]
It may be that although the main error looks nasty it might not be the sticking point, it may be an initialization decision we have to make that will work around it, looking at the error. We see this:
```
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1124)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:169)
```
But the later error that causes compilation to stop is:
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from the command line). io.netty.channel.epoll.Epoll caused initialization of this class with the following trace: 
	at io.netty.util.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)

```

**Comment by aclement** [comment]
For the `webflux-netty` sample, this addition to `compile.sh` enables the program to compile with the exclusions removed from the `pom.xml`. The pom looks much nicer.
```
  --initialize-at-run-time=io.netty.channel.epoll \
```
The runtime initialization also seems to push out the UnsatisfiedLinkError from the output too, because that code isn't running at build time.  I haven't tried a full run of everything (well all netty samples with exclusions removed) yet. That would be the next step.

**Comment by aclement** [comment]
Alright, I put that change into `initialization.json` and ran all the webflux samples with exclusions of epoll thingy removed. They all worked. Pushed it in - let's see if the build machine agrees.  There are other exclusions still in various samples - but I'm unsure if those are in there for size or compatibility reasons? I think for either case we should document the need/reason to do it somewhere if we keep them.
