### ISSUE TITLE
Spring Data JPA and Byte Buddy

### ISSUE THREAD

**Issue by ard333** [spring-projects-experimental/spring-graalvm-native#163]
Hi, I'm trying to build one of my projects that using Spring Data JPA and need to include ``byte-buddy`` to dependencty.

- spring-graal-native 0.7.0.BUILD-SNAPSHOT
- GraalVM Community Edition 20.1.0 (Java 8/11)

Using hybrid feature + agent mode
```
Error: Classes that should be initialized at run time got initialized during image building:
 net.bytebuddy.implementation.bind.annotation.Super$Instantiation was unintentionally initialized at build time. net.bytebuddy.implementation.bind.annotation.Super$Instantiation has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.bytebuddy.implementation.bind.annotation.Super$Instantiation
net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1 was unintentionally initialized at build time. net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1 has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 net.bytebuddy.implementation.bind.annotation.Super$Instantiation was unintentionally initialized at build time. net.bytebuddy.implementation.bind.annotation.Super$Instantiation has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.bytebuddy.implementation.bind.annotation.Super$Instantiation
net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1 was unintentionally initialized at build time. net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1 has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:518)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)
FAILURE: an error occurred when compiling the native-image.
``` 

have tried adding a few of these combinations to ``--initialize-at-build-time``
1. net.bytebuddy.implementation.bind.annotation.Super.Instantiation
2. net.bytebuddy.implementation.bind.annotation.Super$Instantiation
3. net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1
4. net.bytebuddy.implementation.bind.annotation.Super$Instantiation, net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1 
 

but still error.

**Comment by khengsdijk** [comment]
try to add the entire package for initialisation like so:
--initialize-at-build-time=net.bytebuddy.implementation.bind.annotation

**Comment by ard333** [comment]
Thanks @khengsdijk, helped me a lot figuring out how inner class done in native-image option.
