### ISSUE TITLE
Find why DispatcherServlet is initialized on first request on JVM and startup on native image

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#168]
This difference of behavior is a real issue since `DispatcherServlet` early initialization triggers `DispatcherServlet.properties` + reflection initialization which requires more configuration on GraalVM native.

This seems to be triggered by a difference of behavior in Tomcat connection pool on native image, not sure why yet.

With this + https://github.com/spring-projects/spring-framework/issues/25209 and related Spring Fu update, we should be able to remove `DispatcherServlet` substitution.

**Comment by fhanik** [comment]
Hi @sdeleuze 

**Servlet Initialization**

I took a brief look on what boot is doing. Right now, Spring Boot is configuring servlets for lazy initialization. 

When I say initialization, I specifically refer to 
```
javax.servlet.Servlet.init(ServletConfig config);
```

modifying `application.properties` to include the line
```
spring.mvc.servlet.load-on-startup=1
```

will ensure that the DispatcherServlet is loaded and initialized at startup instead of on the first request (first request = default)

When I ran this example, I'm seeing the correct behavior for native-image as well as JVM for both `1` and `-1` values

**DispatcherServlet.properties**

For both JVM and native-image, the `DispatcherServlet.properties` file is loaded when the class is loaded, during application startup. (not on first request)

On the JVM, `DispatcherServlet.properties` is loaded `SpringApplication.run` calls `refreshContext`
On native-image, `DispatcherServlet.properties` is loaded `SpringApplication.run` calls `refreshContext`

***I'm seeing the same behavior for both runtime environments.***

```
java.lang.Exception: FILIP-DispatcherServlet.initStrategies
        at org.springframework.web.servlet.DispatcherServlet.initStrategies(DispatcherServlet.java:505)
        at org.springframework.web.servlet.DispatcherServlet.onRefresh(DispatcherServlet.java:497)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:599)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:777)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by sdeleuze** [comment]
@fhanik I agree with the behavior you describe, but what I was not able to find is how to have the same behavior on JVM and native image with Boot defaults (lazy servlet loading).

On native image, it seems we have an eager loading of the servlet by default (to be confirmed). Is it what you observe as well?

**Comment by sdeleuze** [comment]
After more tests it indeed seems consistent so I close this issue.
