### ISSUE TITLE
Spring GraalVM feature is too strict for spring.factories

### ISSUE THREAD

**Issue by fhanik** [spring-projects-experimental/spring-graalvm-native#169]
Attempting to compile springmvc-tomcat sample while removing a single class from the classpath:

```
org/springframework/boot/autoconfigure/couchbase/CouchbaseAutoConfiguration
```

fails with:

```
rocessing spring.factories - EnableAutoConfiguration lists #127 configurations
Fatal error:org.springframework.graalvm.type.MissingTypeException: Unable to find class file for org/springframework/boot/autoconfigure/couchbase/CouchbaseAutoConfiguration
        at org.springframework.graalvm.type.TypeSystem.resolveSlashed(TypeSystem.java:135)
        at org.springframework.graalvm.type.TypeSystem.resolveSlashed(TypeSystem.java:126)
        at org.springframework.graalvm.type.TypeSystem.resolveDotted(TypeSystem.java:96)
        at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:812)
        at org.springframework.graalvm.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:807)
        at org.springframework.graalvm.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:741)
        at org.springframework.graalvm.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:578)
        at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:122)
        at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:78)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:681)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:681)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:540)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:453)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```

**Comment by aclement** [comment]
As a quick change I would probably make 'cant find it' be the same as 'failed verification' and so the spring.factories will be rewritten with it removed and spring will be happy, never going looking for it. I've put this change in.

**Comment by aclement** [comment]
Just to be clear - the feature was behaving the same as Spring I believe. If you reference things that aren't around it wouldn't work at runtime - but if we actively trim the spring.factories with a change like this we can circumvent that.

**Comment by aclement** [comment]
Final comment - this is only likely to behave if, in addition to trimming classes, the remove unused autoconfig option is ON. But as that is the default now, we should be good...

**Comment by aclement** [comment]
Final final comment - the feature does rewrite spring.factories BUT things may not work that well if you also are using the agent - if the resource list produced by the agent contains spring.factories - you will be including two copies of it - the one we shorten and the original long one which will still refer to the thing you removed. For the moment you should remove the entry from the agent generated resource list. (There should be a warning coming out when the feature notices this is happening to you)
