### ISSUE TITLE
Support @ConstructorBinding

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#172]
Hi,

I add `@ConstructorBinding` to a ConfigurationProperties Class. After that SpringBoot throws an Exception at startup:

```
2020-06-09T21:36:28.8013309Z org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'keycloakConfigRunner' defined in class path resource [de/adorsys/keycloak/config/KeycloakConfigRunner.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'keycloakImportProvider' defined in class path resource [de/adorsys/keycloak/config/provider/KeycloakImportProvider.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'import-de.adorsys.keycloak.config.properties.ImportConfigProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.adorsys.keycloak.config.properties.ImportConfigProperties]: No default constructor found; nested exception is java.lang.NoSuchMethodException: de.adorsys.keycloak.config.properties.ImportConfigProperties.<init>()
2020-06-09T21:36:28.8014550Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[na:na]
2020-06-09T21:36:28.8014905Z 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[na:na]
2020-06-09T21:36:28.8016030Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[na:na]
2020-06-09T21:36:28.8016259Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[na:na]
2020-06-09T21:36:28.8016448Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[na:na]
2020-06-09T21:36:28.8016632Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[na:na]
2020-06-09T21:36:28.8016800Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[na:na]
2020-06-09T21:36:28.8016969Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
2020-06-09T21:36:28.8017133Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[na:na]
2020-06-09T21:36:28.8017296Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[na:na]
2020-06-09T21:36:28.8017506Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:623) ~[na:na]
2020-06-09T21:36:28.8017669Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:611) ~[na:na]
2020-06-09T21:36:28.8017841Z 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1242) ~[na:na]
2020-06-09T21:36:28.8018524Z 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[keycloak-config-cli-native:na]
2020-06-09T21:36:28.8018866Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[keycloak-config-cli-native:na]
2020-06-09T21:36:28.8019186Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[keycloak-config-cli-native:na]
2020-06-09T21:36:28.8019502Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[keycloak-config-cli-native:na]
2020-06-09T21:36:28.8020027Z 	at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:31) [keycloak-config-cli-native:na]
2020-06-09T21:36:28.8021254Z Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'keycloakImportProvider' defined in class path resource [de/adorsys/keycloak/config/provider/KeycloakImportProvider.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'import-de.adorsys.keycloak.config.properties.ImportConfigProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.adorsys.keycloak.config.properties.ImportConfigProperties]: No default constructor found; nested exception is java.lang.NoSuchMethodException: de.adorsys.keycloak.config.properties.ImportConfigProperties.<init>()
2020-06-09T21:36:28.8036547Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[na:na]
2020-06-09T21:36:28.8036770Z 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[na:na]
2020-06-09T21:36:28.8036969Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[na:na]
2020-06-09T21:36:28.8037411Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[na:na]
2020-06-09T21:36:28.8037644Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[na:na]
2020-06-09T21:36:28.8037832Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[na:na]
2020-06-09T21:36:28.8038016Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[na:na]
2020-06-09T21:36:28.8038246Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
2020-06-09T21:36:28.8038431Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[na:na]
2020-06-09T21:36:28.8038605Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[na:na]
2020-06-09T21:36:28.8038782Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
2020-06-09T21:36:28.8045290Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306) ~[na:na]
2020-06-09T21:36:28.8045524Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226) ~[na:na]
2020-06-09T21:36:28.8045722Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[na:na]
2020-06-09T21:36:28.8045904Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[na:na]
2020-06-09T21:36:28.8046059Z 	... 17 common frames omitted
2020-06-09T21:36:28.8047282Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'import-de.adorsys.keycloak.config.properties.ImportConfigProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.adorsys.keycloak.config.properties.ImportConfigProperties]: No default constructor found; nested exception is java.lang.NoSuchMethodException: de.adorsys.keycloak.config.properties.ImportConfigProperties.<init>()
2020-06-09T21:36:28.8047691Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1320) ~[na:na]
2020-06-09T21:36:28.8047871Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214) ~[na:na]
2020-06-09T21:36:28.8048160Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[na:na]
2020-06-09T21:36:28.8048348Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[na:na]
2020-06-09T21:36:28.8048521Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[na:na]
2020-06-09T21:36:28.8048689Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
2020-06-09T21:36:28.8048860Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[na:na]
2020-06-09T21:36:28.8049025Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[na:na]
2020-06-09T21:36:28.8049196Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
2020-06-09T21:36:28.8049366Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306) ~[na:na]
2020-06-09T21:36:28.8049538Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226) ~[na:na]
2020-06-09T21:36:28.8049711Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[na:na]
2020-06-09T21:36:28.8049880Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[na:na]
2020-06-09T21:36:28.8050033Z 	... 31 common frames omitted
2020-06-09T21:36:28.8050225Z Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.adorsys.keycloak.config.properties.ImportConfigProperties]: No default constructor found; nested exception is java.lang.NoSuchMethodException: de.adorsys.keycloak.config.properties.ImportConfigProperties.<init>()
2020-06-09T21:36:28.8050615Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[na:na]
2020-06-09T21:36:28.8050790Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312) ~[na:na]
2020-06-09T21:36:28.8050948Z 	... 43 common frames omitted
2020-06-09T21:36:28.8051111Z Caused by: java.lang.NoSuchMethodException: de.adorsys.keycloak.config.properties.ImportConfigProperties.<init>()
2020-06-09T21:36:28.8051281Z 	at java.lang.Class.getConstructor0(DynamicHub.java:3082) ~[na:na]
2020-06-09T21:36:28.8051483Z 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178) ~[na:na]
2020-06-09T21:36:28.8051648Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[na:na]
2020-06-09T21:36:28.8051803Z 	... 44 common frames omitted
2020-06-09T21:36:28.8051902Z 
```

**Comment by aclement** [comment]
Fixed (at least the case I could create in a testcase).
