### ISSUE TITLE
Unable to use spring cloud config

### ISSUE THREAD

**Issue by itzikiusa** [spring-projects-experimental/spring-graalvm-native#187]
```g.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.springframework.cloud.bootstrap.BootstrapImportSelectorConfiguration]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/cloud/bootstrap/BootstrapImportSelector.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319) ~[player-details-orchestrator-executable:na]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236) ~[player-details-orchestrator-executable:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[na:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [player-details-orchestrator-executable:na]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[na:na]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212) [player-details-orchestrator-executable:na]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117) [player-details-orchestrator-executable:na]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74) [player-details-orchestrator-executable:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [player-details-orchestrator-executable:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [player-details-orchestrator-executable:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [player-details-orchestrator-executable:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) [player-details-orchestrator-executable:na]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) [player-details-orchestrator-executable:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [player-details-orchestrator-executable:na]
	at com.player.details.orchestrator.OrchestratorGatewayApplication.main(OrchestratorGatewayApplication.java:25) [player-details-orchestrator-executable:na]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/bootstrap/BootstrapImportSelector.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[player-details-orchestrator-executable:na]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[na:na]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[na:na]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getRelated(ConfigurationClassParser.java:1086) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getAnnotationAttributes(ConfigurationClassParser.java:1070) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.collectImports(ConfigurationClassParser.java:548) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:521) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:310) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174) ~[na:na]
`
using the example from:
https://spring.io/blog/2020/06/16/spring-tips-spring-and-graalvm-pt-2

**Comment by dsyer** [comment]
That example didn't use Spring Cloud though. The only samples we have that use Spring Cloud are for functions, so I wouldn't expect it to work out of the box yet.

**Comment by itzikiusa** [comment]
@dsyer 
yeah, i know, just thought adding this dependency might work as well.
thanks for the response

**Comment by fluoxa** [comment]
I'm also interestes in this feature. I was trying to compile our application to a native image, but for now i have to cancel my trials

**Comment by sdeleuze** [comment]
Should now be supported, please reopen if that's not the case.
