### ISSUE TITLE
Can't create an ObjenesisCglibAopProxy since it is unsupported in native images

### ISSUE THREAD

**Issue by ard333** [spring-projects-experimental/spring-graalvm-native#197]
Hi I'm using hybrid mode to compile simple CRUD application and try to add ``@Transactional``, successfully compiled, but when it runs, I got this error
``Caused by: org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images``

[here is the difference](https://github.com/ard333/native-binaries-benchmark/commit/67b4630304a34fa074ddc3627c375eee3882a5d9) before and after add ``@Transactional``.

Full stack trace:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceController': Unsatisfied dependency expressed through field 'resourceService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceService' defined in class path resource [com/ard333/nativebinariesbenchmark/springboot/ResourceService.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[na:na]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[na:na]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-boot:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[na:na]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot:na]
	at com.ard333.nativebinariesbenchmark.springboot.Application.main(Application.java:11) ~[spring-boot:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceService' defined in class path resource [com/ard333/nativebinariesbenchmark/springboot/ResourceService.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[na:na]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224) ~[na:na]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[na:na]
	... 20 common frames omitted
Caused by: org.springframework.aop.framework.AopConfigException: Can't create an ObjenesisCglibAopProxy since it is unsupported in native images
	at org.springframework.aop.framework.DefaultAopProxyFactory.createAopProxy(DefaultAopProxyFactory.java:27) ~[na:na]
	at org.springframework.aop.framework.ProxyCreatorSupport.createAopProxy(ProxyCreatorSupport.java:105) ~[na:na]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[na:na]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471) ~[spring-boot:na]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350) ~[spring-boot:na]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-boot:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[na:na]
	... 29 common frames omitted
```

**Comment by sdeleuze** [comment]
This is not supported since native images can't support `@Transactional` on classes for now, only on interfaces (this limitation could be relaxed later but not short term).

@aclement Do you think we could detect that and raise a more easy to understand error?

**Comment by ard333** [comment]
Thank's for the answer @sdeleuze.
