### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-graalvm-native#198]
Hi

I'm trying to run native image based on springmvc-tomcat sample application. Everything is almost fine. Native image is built successfully, Spring Boot application starts successfully. But when I try to hit http://localhost:8080/ endpoint, I get the following exception:

```
Caused by: org.springframework.beans.factory.BeanInitializationException: Could not find DispatcherServlet's default strategy class [org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver] for interface
 [org.springframework.web.servlet.LocaleResolver]; nested exception is java.lang.ClassNotFoundException: org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver
        at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategies(DispatcherServlet.java:873)
        at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategy(DispatcherServlet.java:842)
        at org.springframework.web.servlet.DispatcherServlet.initLocaleResolver(DispatcherServlet.java:555)
        at org.springframework.web.servlet.DispatcherServlet.initStrategies(DispatcherServlet.java:504)
        at org.springframework.web.servlet.DispatcherServlet.onRefresh(DispatcherServlet.java:495)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:599)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)

```

Here's my command to build native image:

```
native-image --verbose \
       -H:EnableURLProtocols=http \
       -H:Name=spring-graalvm \
       -Dspring.native.remove-yaml-support=true \
       -Dspring.native.remove-jmx-support=true \
       -Dspring.xml.ignore=true \
       -Dspring.spel.ignore=true \
       -cp $CP com.example.MainApplication
```

Maven dependencies:
```

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-websocket</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.experimental</groupId>
			<artifactId>spring-graalvm-native</artifactId>
			<version>0.8.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
		</dependency>
	</dependencies>
```

**Comment by aclement** [comment]
Can you try with a quick manual config entry to see if it helps? (Just want to flush everything out before folding the change into spring-graalvm-native)

Create a file in src/main/resources/META-INF/native-image/reflect-config.json that looks like this:
```
[{"name":"org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver","allDeclaredConstructors":true}]
```
Then do another build - did that help?

**Comment by sdeleuze** [comment]
Could you please share what version of Spring Boot you are using? My guess is that you are not using Spring Boot `2.4.0-SNAPSHOT` as required (see https://github.com/spring-projects-experimental/spring-graalvm-native#baseline).
