### ISSUE TITLE
Unable to run native image for spring boot 2.3.1-RELEASE

### ISSUE THREAD

**Issue by sendev1** [spring-projects-experimental/spring-graalvm-native#213]
Hi,

Trying to findout the production ready spring boot release that works with tomcat 9 for spring graal native image
The samples present here in github is using spring boot 2.4.0-SNAPSHOT and spring framework verion 5.3.0-SNAPSHOT.

As per the documentation the supported spring boot version for spring graal vm is 2.3.1. So updated pom to use spring boot version 2.3.1.RELEASE and commented out spring-framework.version.
`<properties>
		<java.version>1.8</java.version>
		
		<tomcat.version>9.0.30</tomcat.version>
	</properties>`

Installed graal vm 20.1.0 in windows machine and created image for springmvc-tomcat app using just spring feature and while running image received following error
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator.<init>()
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1318) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1216) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:173) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:725) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[springmvc-2.3.1-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[springmvc-2.3.1-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[springmvc-2.3.1-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[springmvc-2.3.1-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[springmvc-2.3.1-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[springmvc-2.3.1-tomcat.exe:na]
        at com.example.tomcat.TomcatApplication.main(TomcatApplication.java:10) [springmvc-2.3.1-tomcat.exe:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator.<init>()
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1310) ~[na:na]
        ... 18 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3082) ~[na:na]
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[na:na]
        ... 19 common frames omitted
```

So created image with spring boot 2.3.1 version in hybrid mode because spring feature alone did not work. When I try to run the image I am seeing following error. 

```
2020-07-24 13:24:44.865  INFO 13956 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-07-24 13:24:44.866  INFO 13956 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-07-24 13:24:44.890  INFO 13956 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-07-24 13:24:44.890  INFO 13956 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 454 ms
2020-07-24 13:24:44.893 ERROR 13956 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'formContentFilter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.filter.OrderedFormContentFilter]: Factory method 'formContentFilter' threw exception; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method javax.xml.transform.FactoryFinder.find(Class, String) is reachable
2020-07-24 13:24:44.902  INFO 13956 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-07-24 13:24:44.902  WARN 13956 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2020-07-24 13:24:44.905  INFO 13956 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-24 13:24:44.908 ERROR 13956 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at com.example.tomcat.TomcatApplication.main(TomcatApplication.java:10) [springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:437) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158) ~[na:na]
        ... 9 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'formContentFilter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.filter.OrderedFormContentFilter]: Factory method 'formContentFilter' threw exception; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method javax.xml.transform.FactoryFinder.find(Class, String) is reachable
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[na:na]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:483) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[na:na]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211) ~[na:na]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:174) ~[na:na]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:169) ~[na:na]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAdaptableBeans(ServletContextInitializerBeans.java:154) ~[na:na]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:255) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:229) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[na:na]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[na:na]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[na:na]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:459) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[na:na]
        ... 14 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.filter.OrderedFormContentFilter]: Factory method 'formContentFilter' threw exception; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method javax.xml.transform.FactoryFinder.find(Class, String) is reachable
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[na:na]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[na:na]
        ... 55 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method javax.xml.transform.FactoryFinder.find(Class, String) is reachable
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86) ~[na:na]
        at javax.xml.transform.FactoryFinder.find(FactoryFinder.java:206) ~[na:na]
        at javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:106) ~[na:na]
        at org.springframework.http.converter.xml.AbstractXmlHttpMessageConverter.<init>(AbstractXmlHttpMessageConverter.java:52) ~[na:na]
        at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.<init>(AbstractJaxb2HttpMessageConverter.java:38) ~[na:na]
        at org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter.<init>(Jaxb2RootElementHttpMessageConverter.java:64) ~[na:na]
        at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:72) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.<init>(FormContentFilter.java:61) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.web.servlet.filter.OrderedFormContentFilter.<init>(OrderedFormContentFilter.java:29) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration.formContentFilter(WebMvcAutoConfiguration.java:164) ~[springmvc-2.3.1-agent-spring-5.2.7-tomcat.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[na:na]
        ... 56 common frames omitted
```

**Comment by sendev1** [comment]
Update:

So I switch spring-graalvm-native to 0.7.1 instead of 0.8.0-SNAPSHOT and spring boot web app in 2.3.1-RELEASE started working. But I had to use the hybrid mode to generate the image. Hope this will be helpful for some one.

**Comment by sdeleuze** [comment]
Yeah with Spring Boot 2.3.1 you should use 0.7.1 as documented which misses various improvement we made on 0.8.0-SNAPSHOT (requires Boot 2.4.x).
