### ISSUE TITLE
StringIndexOutOfBoundsException in 0.7.0 is now NullPointerException in 0.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by DrNaughtyDog** [spring-projects-experimental/spring-graalvm-native#234]
I am trying  to compile a maven project with postgresql and jpa drivers and OpenJDK Runtime Environment (build 1.8.0_252-b09) OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 

On 
        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-graalvm-native</artifactId>
            <version>0.7.1</version>
        </dependency>

i get the following error

```
Fatal error:java.lang.StringIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.springframework.graalvm.type.TypeSystem.resolve(TypeSystem.java:208)
	at org.springframework.graalvm.type.Method.getReturnType(Method.java:199)
	at org.springframework.graalvm.type.Type.collectAtMappingMarkedReturnTypes(Type.java:1655)
	at org.springframework.graalvm.support.ResourcesHandler.processResponseBodyComponent(ResourcesHandler.java:428)
	at org.springframework.graalvm.support.ResourcesHandler.processSpringComponents(ResourcesHandler.java:310)
	at org.springframework.graalvm.support.ResourcesHandler.processExistingOrSynthesizedSpringComponentsFiles(ResourcesHandler.java:177)
	at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:124)
	at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:78)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

```

Heres the rest of my pom.xml if that helps.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>postgres</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for postgresql native-image</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>

        <!--  -->
        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-graalvm-native</artifactId>
            <version>0.8.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>2.3.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>


            <plugin>
                <groupId>org.hibernate.orm.tooling</groupId>
                <artifactId>hibernate-enhance-maven-plugin</artifactId>
                <version>${hibernate.version}</version>
                <executions>
                    <execution>
                        <configuration>
                            <failOnError>true</failOnError>
                            <enableLazyInitialization>true</enableLazyInitialization>
                            <enableDirtyTracking>true</enableDirtyTracking>
                            <enableExtendedEnhancement>false</enableExtendedEnhancement>
                        </configuration>
                        <goals>
                            <goal>enhance</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>
        <pluginRepository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>

```

When i tried to upgrade to version 

        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-graalvm-native</artifactId>
            <version>0.8.0-SNAPSHOT</version>
        </dependency>

i get yet another error.

```
Fatal error:java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
Caused by: java.lang.NullPointerException
	at org.springframework.graalvm.support.ResourcesHandler.processResponseBodyComponent(ResourcesHandler.java:586)
	at org.springframework.graalvm.support.ResourcesHandler.processSpringComponents(ResourcesHandler.java:454)
	at org.springframework.graalvm.support.ResourcesHandler.handleSpringComponents(ResourcesHandler.java:248)
	at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:147)
	at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:88)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

```
Is there any information on why this behaviour occurs or how to fix this? 
Thanks a lot

**Comment by aclement** [comment]
If you turn on the option `-Dspring.native.verbose=true` and re-run, you should see an output line:

```
"Found these return types from Mapped methods in "+t.getName()+" > "+returnTypes
```
I suspect one of those return types is null. I'd be interested to see what kind of request mappings you are using that leads to it (what do the the mappings declared in the specified type look like? What are the return types?)

In the interim I have also put in a guard that should mean snapshots can get further.

**Comment by DrNaughtyDog** [comment]
Hi Andy, thanks for the quick reply. Here's the corresponding stackoverflow post with all the details about this sample project https://stackoverflow.com/questions/63449526/graalvm-native-image-with-spring-boot-postgresql-just-wont-build , I hope it helps. All I'm trying to achieveis to generate a spring app with postgresql drivers as a native-image. I'm curious how to make this work.

**Comment by aclement** [comment]
Have you tried it now I've put the fix in to cope with null? (I'm still interested in what your mappings look like).  I would recommend working with the latest, 0.7.1 is getting a bit old now but I do know that probably requires using recent Spring Boot.

**Comment by DrNaughtyDog** [comment]
Sorry for the late reply, I tried it with your fix and it seems to have resolved the issue, thank you! My application is starting up, yet when calling the restcontroller it throws the following exception. At the moment i cannot tell if this is a bug or a configuration issue.

```
org.springframework.beans.factory.BeanInitializationException: Could not find DispatcherServlet's default strategy class [org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver] for interface [org.springframework.web.servlet.LocaleResolver]; nested exception is java.lang.ClassNotFoundException: org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver
	at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategies(DispatcherServlet.java:873)
	at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategy(DispatcherServlet.java:842)
	at org.springframework.web.servlet.DispatcherServlet.initLocaleResolver(DispatcherServlet.java:555)
	at org.springframework.web.servlet.DispatcherServlet.initStrategies(DispatcherServlet.java:504)
	at org.springframework.web.servlet.DispatcherServlet.onRefresh(DispatcherServlet.java:495)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:599)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:777)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1207)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategies(DispatcherServlet.java:868)
	... 28 more

```
I tried your fix in another project with postgresql, the resource-config.json is including org.postgresql.translation.messages, yet the following stacktrace is printed during build time.

```
[jpa:26727]        setup:   2,455.76 ms,  1.83 GB
Fatal error:java.util.MissingResourceException: Can't find bundle for base name org.postgresql.translation.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
	at com.oracle.svm.util.ModuleSupport.getResourceBundle(ModuleSupport.java:45)
	at com.oracle.svm.core.jdk.LocalizationFeature.addBundleToCache(LocalizationFeature.java:261)
	at com.oracle.svm.hosted.ResourcesFeature$ResourcesRegistryImpl.addResourceBundles(ResourcesFeature.java:87)
	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseEntry(ResourceConfigurationParser.java:90)
	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseTopLevelObject(ResourceConfigurationParser.java:71)
	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseAndRegister(ResourceConfigurationParser.java:47)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:132)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:479)
	at java.util.stream.IntPipeline.sum(IntPipeline.java:437)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
	at com.oracle.svm.hosted.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:100)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

```
If you want i can open this in a new issue. The problems seen to be similar.

**Comment by aclement** [comment]
Theres a couple of options here. It looks like we are missing a hint for reflective access to `AcceptHeaderLocaleResolver` when doing the kind of thing you are doing. You can:

1) Use the agent to collect extra config that is missing and supply that into the native-image process too. Basically start up your app with the agent attached (pointing it to some folder to dump findings in) then exercise your endpoints. Then native-image build with that dump folder on the class path.

2) Manually add a simple reflect-config.json that includes this one type, could be quick and easy if it is the only one. But if you uncover a whole set of them option (1) is more appealing.

The proper fix would be to get a hint added in our base project. It'd be nice to see the kind of controller/mapping that triggered it, but we can work that out if it isn't easy for you to tell. 

In the other project, yeah, could capture that as a separate issue. Did the resource config file definitely specify it is a bundle entry and not a regular pattern? Give it an extra kick with the command line option `-H:IncludeResourceBundles=` maybe?

**Comment by DrNaughtyDog** [comment]
I forgot using the agent to collect the config for the native-image in the project that successfully built, my bad... 
I raised both postgres project to the same level of error now, which is occuring during buildtime.

```
[postgres:15131]        setup:     251.00 ms,  2.11 GB
Fatal error:java.util.MissingResourceException: Can't find bundle for base name org.postgresql.translation.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
	at com.oracle.svm.util.ModuleSupport.getResourceBundle(ModuleSupport.java:45)
	at com.oracle.svm.core.jdk.LocalizationFeature.addBundleToCache(LocalizationFeature.java:261)
	at com.oracle.svm.core.jdk.LocalizationFeature.addResourceBundles(LocalizationFeature.java:245)
	at com.oracle.svm.core.jdk.LocalizationFeature.afterRegistration(LocalizationFeature.java:153)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
```
The culprit org.postgresql.translation.messages is included in the resource-config.json bundles array that the agent automatically configured. I also tried to explicitly include it via parameter as you suggested with `-H:IncludeResourceBundles=org.postgresql.translation.messages ` but it didnt change the stacktrace

resource-config.json
```
  "bundles":[
    {"name":"org.apache.catalina.authenticator.LocalStrings"}, 
    {"name":"org.apache.catalina.authenticator.jaspic.LocalStrings"}, 
    {"name":"org.apache.catalina.connector.LocalStrings"}, 
    {"name":"org.apache.catalina.core.LocalStrings"}, 
    {"name":"org.apache.catalina.deploy.LocalStrings"}, 
    {"name":"org.apache.catalina.loader.LocalStrings"}, 
    {"name":"org.apache.catalina.mapper.LocalStrings"}, 
    {"name":"org.apache.catalina.mbeans.LocalStrings"}, 
    {"name":"org.apache.catalina.realm.LocalStrings"}, 
    {"name":"org.apache.catalina.security.LocalStrings"}, 
    {"name":"org.apache.catalina.session.LocalStrings"}, 
    {"name":"org.apache.catalina.startup.LocalStrings"}, 
    {"name":"org.apache.catalina.util.LocalStrings"}, 
    {"name":"org.apache.catalina.valves.LocalStrings"}, 
    {"name":"org.apache.catalina.webresources.LocalStrings"}, 
    {"name":"org.apache.coyote.LocalStrings"}, 
    {"name":"org.apache.coyote.http11.LocalStrings"}, 
    {"name":"org.apache.coyote.http11.filters.LocalStrings"}, 
    {"name":"org.apache.naming.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.buf.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.compat.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.descriptor.web.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.http.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.http.parser.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.modeler.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.net.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.scan.LocalStrings"}, 
    {"name":"org.apache.tomcat.util.threads.res.LocalStrings"}, 
    {"name":"org.apache.tomcat.websocket.LocalStrings"}, 
    {"name":"org.apache.tomcat.websocket.server.LocalStrings"}, 
    {"name":"org.postgresql.translation.messages"}
  ]
```
Heres my whole native-image command which is executed by script.

```
time native-image \
  --verbose \
  -H:EnableURLProtocols=http \
  -H:+RemoveSaturatedTypeFlows \
  -H:Name=$ARTIFACT \
  -H:+TraceClassInitialization \
  --initialize-at-build-time=org.springframework.util.unit.DataSize \
  -H:+ReportExceptionStackTraces  \
  -H:IncludeResourceBundles=org.postgresql.translation.messages \
  -Dspring.native.verbose=true \
  -Dspring.native.remove-jmx-support=true \
  -Dspring.native.remove-spel-support=true \
  -Dspring.native.remove-yaml-support=true \
  -cp $CP $MAINCLASS  \
  --no-fallback\
  --allow-incomplete-classpath \
  -Dspring.native.remove-xml-support=true
```
the parameters seem to be accepted by the actual native-image build, yet the stacktrace is printed

```
-H:Path=/home/drnd/DVP/exxeta/postgres-native/target/native-image \
-H:EnableURLProtocols=http \
-H:+RemoveSaturatedTypeFlows \
-H:Name=postgres \
-H:+TraceClassInitialization \
-H:ClassInitialization=org.springframework.util.unit.DataSize:build_time \
-H:+ReportExceptionStackTraces \
-H:IncludeResourceBundles=org.postgresql.translation.messages \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+InstallExitHandlers \
-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-reflection.json \
-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-resource.json \
-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-reflection.json \
-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-resource.json \
-H:JNIConfigurationResources=META-INF/native-image/jni-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/reflect-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/resource-config.json \
-H:DynamicProxyConfigurationResources=META-INF/native-image/proxy-config.json \
-H:FallbackThreshold=0 \
-H:+AllowIncompleteClasspath \
-H:CLibraryPath=/usr/graalVM/graalvm-ce-java8-20.1.0/jre/lib/svm/clibraries/linux-amd64 \
-H:Class=com.example.postgres.PostgresApplication \
```

Coming back to your question about the controller/mapping, here are the controllers I am using each project:

Controller1: 
```
package com.example.postgres.controller;

import java.util.List;

import javax.annotation.Resource;

import com.example.postgres.entity.Employee;
import com.example.postgres.service.EmployeeService;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping("/postgresApp")
public class ApplicationController {

	@Resource
	EmployeeService employeeService;
	
	@GetMapping(value = "/employeeList")
	public List<Employee> getEmployees() {
		return employeeService.findAll();
	
	}
	
	@PostMapping(value = "/createEmp")
	public void createEmployee(@RequestBody Employee emp) {
		 employeeService.insertEmployee(emp);
	
	}
	@PutMapping(value = "/updateEmp")
	public void updateEmployee(@RequestBody Employee emp) {
		 employeeService.updateEmployee(emp);
	
	}
	@PutMapping(value = "/executeUpdateEmp")
	public void executeUpdateEmployee(@RequestBody Employee emp) {
		 employeeService.executeUpdateEmployee(emp);
	
	}
	
	@DeleteMapping(value = "/deleteEmpById")
	public void deleteEmployee(@RequestBody Employee emp) {
		 employeeService.deleteEmployee(emp);
	
	}

}
```
Controller2:
```
package com.example.jpa.controller;

import com.example.jpa.entity.Customer;
import com.example.jpa.repository.CustomerRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collection;

@RestController
@RequiredArgsConstructor
public class CustomerRestController {

    private final CustomerRepository customerRepository;

    @GetMapping("/customers")
    Collection<Customer> customers() {
        return this.customerRepository.findAll();
    }
}
```
If theres anything else i can provide, please let me know and thanks for helping me advance in this. I'd really like to see my PostgreSQL up and running :-)

**Comment by aclement** [comment]
I have a spring boot with postgres sample building and working here: https://github.com/aclement/postgress-boot-native
(not quite sure how similar it is to yours... but you might want to take a look).

Key things to keep in mind:
- it is using Boot 2.4.0.M2 - changes to support spring boot projects are not only going into spring-graalvm-native but spring-framework and boot. It is tricky to support older versions of boot simultaneously whilst we try to move quickly. The dispatcherservlet issue you hit above - that won't happen with boot 2.4.0.m2 and spring graalvm native because of changes in framework 5.3 snapshots (which just aren't there in framework 5.2).
- sample uses a docker-compose to run postgres then once app is launched `http localhost:8080/postgressApp/employeeList` to call it. The app is actually from here: https://github.com/jokumar/postgress-boot which I just took today, upgraded to boot 2.4.0.m2, added docker-compose, created a compile.sh script - used the agent to collect config and then it built/ran ok.
- Using GraalVM 20.2 (Java8 flavour).

There is much to improve, I'd rather not require the agent step, but it is a starting point. Let me know how that app differs to yours (other than boot version)

**Comment by aclement** [comment]
I pushed enough configuration hints for Postgres such that my sample project (linked in the previous comment) will now build and run as a native-image without needing to run the agent to collect anything. I'm sure there is more required for more sophisticated samples.

**Comment by aclement** [comment]
Just for reference, this is what I added: https://github.com/spring-projects-experimental/spring-graalvm-native/blob/64e605fb93c623397bf2322997e892c677e5e980/spring-graalvm-native-configuration/src/main/java/org/postgresql/PostgresqlHints.java - was based on any types mentioning postgresql found in the agent collected data.

**Comment by aclement** [comment]
The NPE is fixed and my Postgres sample is working, so I think we're ok, please reopen if still an issue for you, my sample is possibly not representative of your situation.
