### ISSUE TITLE
Add Websocket support

### ISSUE THREAD

**Issue by MuriloFtto** [spring-projects-experimental/spring-graalvm-native#237]
Hello, I'm working on a sample using the websocket in the spring, but I have a problem when I try to disable the proxybean methods of the DelegatingWebSocketMessageBrokerConfiguration.class class, the one I mentioned above extends WebSocketMessageBrokerConfigurationSupport.class which, in turn, extends from AbstractConfassageBroker, called WebSocketMessageBrokerStats.class. The problem is that, for this class, we need the ThreadPoolTaskScheduler bean to be active, but it does not initialize and I get the following exception:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketMessageBrokerStats' defined in class path resource [br/com/sysmo/s1/server/perifericos/api/config/DelegatingWebSocketMessageBrokerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.socket.config.WebSocketMessageBrokerStats]: Factory method 'webSocketMessageBrokerStats' threw exception; nested exception is java.lang.IllegalStateException: ThreadPoolTaskScheduler not initialized
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:483) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at br.com.sysmo.s1.server.perifericos.Application.main(Application.java:23) [classes!/:1.21.7-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [s1-server-perifericos-api-1.21.7-SNAPSHOT.jar:1.21.7-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [s1-server-perifericos-api-1.21.7-SNAPSHOT.jar:1.21.7-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [s1-server-perifericos-api-1.21.7-SNAPSHOT.jar:1.21.7-SNAPSHOT]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) [s1-server-perifericos-api-1.21.7-SNAPSHOT.jar:1.21.7-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.socket.config.WebSocketMessageBrokerStats]: Factory method 'webSocketMessageBrokerStats' threw exception; nested exception is java.lang.IllegalStateException: ThreadPoolTaskScheduler not initialized
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 28 common frames omitted
Caused by: java.lang.IllegalStateException: ThreadPoolTaskScheduler not initialized
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler.getScheduledExecutor(ThreadPoolTaskScheduler.java:155) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler.scheduleWithFixedDelay(ThreadPoolTaskScheduler.java:357) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.scheduling.TaskScheduler.scheduleWithFixedDelay(TaskScheduler.java:182) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.socket.config.WebSocketMessageBrokerStats.initLoggingTask(WebSocketMessageBrokerStats.java:125) ~[spring-websocket-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.socket.config.WebSocketMessageBrokerStats.setSockJsTaskScheduler(WebSocketMessageBrokerStats.java:119) ~[spring-websocket-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurationSupport.webSocketMessageBrokerStats(WebSocketMessageBrokerConfigurationSupport.java:131) ~[spring-websocket-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 29 common frames omitted`

I can reproduce a sample, but if I try to increase the configuration
@Configuration (proxyBeanMethods = false)
public class DelegatingWebSocketMessageBrokerConfiguration extends WebSocketMessageBrokerConfigurationSupport

You will receive the above exception

**Comment by sdeleuze** [comment]
Hi, could you please share a sample project to reproduce?

**Comment by MuriloFtto** [comment]
@sdeleuze, the real problem occurs when I use the
proxyBeanMethods = false in 
@EnableWebSocketMessageBroker 

example:
https://github.com/MuriloFtto/examplenative.git

you can start with
**git clone https://github.com/MuriloFtto/examplenative.git**
*mvn clean install**
**java -jar target/demo-0.0.1-SNAPSHOT.jar**

thank you

**Comment by sdeleuze** [comment]
There are indeed cross beans invocations in `WebSocketMessageBrokerConfigurationSupport` which can't be supported by native.

@rstoyanchev Any chance we could change `WebSocketMessageBrokerConfigurationSupport` to avoid cross `@Bean` invocation and allow using `@Configuration(proxyBeanMethods = false)` in `DelegatingWebSocketMessageBrokerConfiguration` in Spring Framework 5.3 timeframe or is it too much breaking change?

**Comment by rstoyanchev** [comment]
Certainly something to consider soon and decide based on the result.

**Comment by MuriloFtto** [comment]
Does that help ?, We modified the websocket to work.

https://github.com/MuriloFtto/WebscoketExample

This repository has a modified library

**Comment by sdeleuze** [comment]
This now should be possible thanks to [those changes](https://github.com/spring-projects/spring-framework/commit/017242463502f451c6c71a823b9c5232276dd78e) in Spring Framework. Notice it will require some reflection 
configuration since `ParameterNameDiscoverer` needs to be able to recognize parameter names to differentiate the beans to inject.
