### ISSUE TITLE
Spring security + actuator fail on SecurityRequestMatchersManagementContextConfiguration

### ISSUE THREAD

**Issue by WeirdBob** [spring-projects-experimental/spring-graalvm-native#238]
Hi,

If I take the security sample and just add the spring-boot-starter-actuator dependency in the pom.xml, the resulting binary fails at runtime with:
```
org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [org.springframework.boot.actuate.autoconfigure.security.servlet.SecurityRequestMatchersManagementContextConfiguration]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:436) ~[security:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:273) ~[security:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:134) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[security:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751) ~[security:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:410) ~[security:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[security:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1280) ~[security:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1269) ~[security:na]
        at com.example.securingweb.SecuringWebApplication.main(SecuringWebApplication.java:10) ~[security:na]
```

which is weird because SecurityRequestMatchersManagementContextConfiguration is already marked (indirectly) with proxyBeanMethods=false.

It also happens on my personal project, removing actuator fixed it.

**Comment by sdeleuze** [comment]
Probably fixed by https://github.com/spring-projects/spring-boot/commit/5d20660c8a026bfd73259488f162f222e739382c.
