### ISSUE TITLE
Petclinic samples fail with missing reflection config

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#281]
```
petclinic-jdbc_1  | SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.view.InternalResourceView]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.web.servlet.view.InternalResourceView.<init>()] with root cause
petclinic-jdbc_1  | java.lang.NoSuchMethodException: org.springframework.web.servlet.view.InternalResourceView.<init>()
petclinic-jdbc_1  | 	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
petclinic-jdbc_1  | 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
petclinic-jdbc_1  | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:140)
petclinic-jdbc_1  | 	at org.springframework.web.servlet.view.UrlBasedViewResolver.buildView(UrlBasedViewResolver.java:553)
petclinic-jdbc_1  | 	at org.springframework.web.servlet.view.InternalResourceViewResolver.buildView(InternalResourceViewResolver.java:106)
...
```

It's strange because Petclinic has always needed to use `InternalResourceView` so I don't know how it ever worked.

**Comment by dsyer** [comment]
I tried it with this `reflect-config.json` and it worked

```
[
    {
        "name": "org.springframework.web.servlet.view.InternalResourceView",
        "allDeclaredConstructors": true
    }
]
```

so I guess a hint will be easy to craft.

**Comment by aclement** [comment]
Fixed. Although why this is now required config, hmmm...
