### ISSUE TITLE
spring.autoconfigure.exclude results into runtime errors.

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#282]
Hi,

since https://github.com/spring-projects-experimental/spring-graalvm-native/issues/142 is not resolved, I created a spring profile for all graalvm build contain an exclude for a specific class:

```
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
```

The spring boot profile is enabled by default for all native build via `spring.profiles.active`.
It allows me to disable the whole @Validation logic without any code changes.

While this pattern work fine until 0.7, it wont work since 0.8.

Error while start the application:
```
2020-09-16 10:36:05.427 ERROR 3343 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Unable to read meta-data for class org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:237) ~[na:na]
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getOrder(AutoConfigurationSorter.java:208) ~[na:na]
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.access$000(AutoConfigurationSorter.java:154) ~[na:na]
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.lambda$getInPriorityOrder$0(AutoConfigurationSorter.java:63) ~[na:na]
	at java.util.TimSort.binarySort(TimSort.java:296) ~[na:na]
	at java.util.TimSort.sort(TimSort.java:221) ~[na:na]
	at java.util.Arrays.sort(Arrays.java:1512) ~[na:na]
	at java.util.ArrayList.sort(ArrayList.java:1464) ~[keycloak-config-cli-native:na]
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.getInPriorityOrder(AutoConfigurationSorter.java:62) ~[na:na]
...
```
See: https://github.com/adorsys/keycloak-config-cli/pull/169/checks?check_run_id=1122593770 for full stack trace.

It looks like classes excluded by `spring.autoconfigure.exclude` are not inside the native build.

Setting `-Dspring.native.remove-unused-autoconfig=false` inside pom.xml won't help since it results in build errors:

```
...
Processing META-INF/spring.factories files...
spring.factories processing, problem adding access for key org.springframework.boot.liquibase.LiquibaseChangelogMissingFailureAnalyzer: liquibase/exception/ChangeLogParseException
Processing spring.factories - PropertySourceLoader lists #2 property source loaders
spring.factories processing, problem adding access for key org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer: org/springframework/jdbc/CannotGetJdbcConnectionException
Processing spring.factories - EnableAutoConfiguration lists #130 configurations
Fatal error:java.lang.NoClassDefFoundError
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
  at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
  at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
  at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
Caused by: java.lang.NoClassDefFoundError: org/springframework/amqp/rabbit/config/RetryInterceptorBuilder
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.getDeclaredConstructor(Class.java:2178)
  at com.oracle.svm.hosted.config.ReflectionRegistryAdapter.registerConstructor(ReflectionRegistryAdapter.java:137)
  at org.springframework.graalvm.support.ReflectionHandler.addAccess(ReflectionHandler.java:417)
  at org.springframework.graalvm.support.ResourcesHandler.registerAllRequested(ResourcesHandler.java:1537)
  at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1454)
  at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1435)
  at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1038)
  at org.springframework.graalvm.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:1028)
  at org.springframework.graalvm.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:927)
  at org.springframework.graalvm.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:694)
  at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:138)
  at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:107)
  at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:693)
  at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
  at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:693)
  at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
  at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
  at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: java.lang.ClassNotFoundException: org.springframework.amqp.rabbit.config.RetryInterceptorBuilder
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 25 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 min
[INFO] Finished at: 2020-09-16T10:09:50Z
[INFO] ------------------------------------------------------------------------
```

Full build logs here: https://github.com/adorsys/keycloak-config-cli/runs/1122503489

**Comment by aclement** [comment]
I don't think this is an issue any longer. We have code that looks at `spring.autoconfigure.exclude` and if something is listed and the feature was going to throw it out, we'll still add the reflective data for it so that the spring.autoconfig.exclude processing won't fail (effectively, ironically, the exclusion is going to make the image bigger and use more memory...).  Now this code only handles the case for the property being set in `application*.properties` - if it is set somewhere else we won't catch this scenario. It is a bit of an anti-pattern to exclude things that were already not going to be used. You don't mention in which properties file you were setting the exclusion.

I've taken two samples (commandlinerunner, validator) and run them both with the exclude pattern above. commandlinerunner would be actively be discarding validation config and validator sample will be using it. With the exclusion specified, both of these worked fine. I would need a sample showing the issue to dig into it further I think. do let me know if you were putting the exclusion somewhere else too... hmm, maybe it is profile related.

supporting full property resolution with profile awareness is not something I want to build into the feature right now. So I'd say if you want to get complicated config to work, use the agent to collect what you need, or in this case just create a `META-INF/native-image/reflect-config.json` file containing one entry for the configuration you are excluding.
