### ISSUE TITLE
spring.xml.ignore=false causes NullPointerException in TypeSystem

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-graalvm-native#286]
Adding the `-Dpring.xml.ignore=false` causes a NPE in `o.s.graalvm.type.TypeSystem.findActiveDefaultHints(TypeSystem.java:679)` at build time.

Without the flag xml support is disabled, which leads to an `UnsupportedOperationException: XML support disabled` on startup.

Sample Project: [spring-graalvm-native-samples/data-rest](https://github.com/christophstrobl/spring-graalvm-native/tree/issue/192/spring-graalvm-native-samples/spring-data-rest)

Full Stack Trace:
```bash
Excluding 95 auto-configurations from spring.factories file
WARNING: unable to trim META-INF/spring.factories (for example to disable unused auto configurations) because an existing resource-config is directly including it: /home/cstrobl/spring-graalvm-native/spring-graalvm-native-samples/spring-data-rest/target/native-image/BOOT-INF/classes/META-INF/native-image/resource-config.json
Fatal error:java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
Caused by: java.lang.NullPointerException
	at org.springframework.graalvm.type.TypeSystem.findActiveDefaultHints(TypeSystem.java:679)
	at org.springframework.graalvm.support.ResourcesHandler.handleConstantHints(ResourcesHandler.java:169)
	at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:131)
	at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:107)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:693)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:693)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
```

**Comment by aclement** [comment]
Fixed
