### ISSUE TITLE
InternalResourceView error with 0.8.1-SNAPSHOT on petclinic-jpa homepage

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#288]
```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.view.InternalResourceView]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.web.servlet.view.InternalResourceView.<init>()] with root cause
java.lang.NoSuchMethodException: org.springframework.web.servlet.view.InternalResourceView.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:140)
	at org.springframework.web.servlet.view.UrlBasedViewResolver.buildView(UrlBasedViewResolver.java:553)
	at org.springframework.web.servlet.view.InternalResourceViewResolver.buildView(InternalResourceViewResolver.java:106)
	at org.springframework.web.servlet.view.UrlBasedViewResolver.loadView(UrlBasedViewResolver.java:530)
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.createView(AbstractCachingViewResolver.java:275)
	at org.springframework.web.servlet.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:495)
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.resolveViewName(AbstractCachingViewResolver.java:184)
	at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.getCandidateViews(ContentNegotiatingViewResolver.java:310)
	at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.resolveViewName(ContentNegotiatingViewResolver.java:228)
	at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1436)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1372)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1140)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1079)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
```

**Comment by aclement** [comment]
Fixed. Although why this is now required config, hmmm...
