### ISSUE TITLE
InstantiationException is thrown when using Bean Validation

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects-experimental/spring-graalvm-native#297]
I tried to use Spring Boot with Hibernate Validator which should work according to https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-docs/src/main/asciidoc/support.adoc
However, I get a stacktrace (see below) when I start the Docker container. A testcase is attached.

Just invoke `./gradlew bootBuildImage` and `docker run --publish 8080:8080 --name testcase --rm testcase:1.0`.

The stacktrace:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[na:na]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:770) ~[testcase.ApplicationKt:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[testcase.ApplicationKt:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:421) ~[testcase.ApplicationKt:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329) ~[testcase.ApplicationKt:na]
        at testcase.ApplicationKt.main(Application.kt:28) ~[na:na]
Caused by: java.lang.ExceptionInInitializerError: null
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291) ~[na:na]
        at org.hibernate.validator.internal.engine.ValidatorFactoryConfigurationHelper.determineGetterPropertySelectionStrategy(ValidatorFactoryConfigurationHelper.java:286) ~[na:na]
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:176) ~[na:na]
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[testcase.ApplicationKt:na]
        at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:448) ~[na:na]
        at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:310) ~[testcase.ApplicationKt:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[na:na]
        ... 15 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ReusableMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at org.apache.logging.log4j.spi.AbstractLogger.createDefaultMessageFactory(AbstractLogger.java:231) ~[na:na]
        at org.apache.logging.log4j.spi.AbstractLogger.<init>(AbstractLogger.java:132) ~[na:na]
        at org.apache.logging.slf4j.SLF4JLogger.<init>(SLF4JLogger.java:44) ~[na:na]
        at org.apache.logging.slf4j.SLF4JLoggerContext.getLogger(SLF4JLoggerContext.java:39) ~[na:na]
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:669) ~[na:na]
        at org.jboss.logging.Log4j2Logger.<init>(Log4j2Logger.java:36) ~[na:na]
        at org.jboss.logging.Log4j2LoggerProvider.getLogger(Log4j2LoggerProvider.java:30) ~[na:na]
        at org.jboss.logging.Log4j2LoggerProvider.getLogger(Log4j2LoggerProvider.java:26) ~[na:na]
        at org.jboss.logging.Logger.getLogger(Logger.java:2465) ~[na:na]
        at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2573) ~[na:na]
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530) ~[na:na]
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516) ~[na:na]
        at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:22) ~[na:na]
        at org.hibernate.validator.internal.properties.DefaultGetterPropertySelectionStrategy.<clinit>(DefaultGetterPropertySelectionStrategy.java:26) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271) ~[na:na]
        ... 22 common frames omitted
Caused by: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ReusableMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at java.lang.Class.newInstance(DynamicHub.java:850) ~[na:na]
        at org.apache.logging.log4j.spi.AbstractLogger.createDefaultMessageFactory(AbstractLogger.java:228) ~[na:na]
        ... 37 common frames omitted
```
[testcase.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5261674/testcase.zip)

**Comment by dsyer** [comment]
I don't think we support log4j yet in native images. How about truing again with logback (or JDK logging)? And thanks for the sample - any chance you could do one with Java? I made one a bit like yours and it seems to work to me, but I'd be happy to have a test case.

**Comment by juergenzimmermann** [comment]
@dsyer When I exclude `org.apache.logging.log4j:log4j-to-slf4j` from the Gradle dependencies then the issue is gone. The dependency tree from `gradle dependencies` looks like:

```
+--- org.springframework.boot:spring-boot-starter-webflux -> 2.4.0-M3
|    +--- org.springframework.boot:spring-boot-starter:2.4.0-M3
...
|    |    +--- org.springframework.boot:spring-boot-starter-logging:2.4.0-M3
|    |    |    +--- ch.qos.logback:logback-classic:1.2.3
|    |    |    |    +--- ch.qos.logback:logback-core:1.2.3
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.13.3
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.13.3
|    |    |    \--- org.slf4j:jul-to-slf4j:1.7.30
|    |    |         \--- org.slf4j:slf4j-api:1.7.30
```

Next week I'll attach a Java-based testcase.

**Comment by dsyer** [comment]
You shouldn't have to exclude the log4j API (I didn't in my sample). It will be helpful to have a test case.
