### ISSUE TITLE
Support for hsqldb

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#303]
We have h2 working with the petclinic. It might help people to get started if hsqldb worked as well.

**Comment by Query-Interface** [comment]
Hello,
I was able to make it work with some additional settings in a project similar to pet-clinic. I used graalvm graalvm-ce-java11-20.2.0, spring boot 2.4.0-M3 and native-image-maven-plugin 0.8.1. 

Here are the additional settings:

- in the native-image buildargs  -H:IncludeResourceBundles=org.hsqldb.resources.sql-state-messages
- in reflect-config.json: 
{
	 "name": "org.hibernate.dialect.HSQLDialect",
	 "allDeclaredFields": true,
	 "allDeclaredConstructors": true,
	 "allDeclaredMethods": true
	},
	{
	 "name": "org.hsqldb.dbinfo.DatabaseInformationFull",
	 "allDeclaredFields": true,
	 "allDeclaredConstructors": true,
	 "allDeclaredMethods": true
	}

- in resource-config.json:
{
  "resources":[
	{"pattern":"org/hsqldb/resources/information-schema.sql"},
	{"pattern":"org/hsqldb/resources/lob-schema.sql"}
  ]
}

I also have to add org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl in reflect-config.json, but I do not think it is linked to hsqldb.

I have tested on Windows10 with hsqldb in file mode.

Hope it can help.

**Comment by aclement** [comment]
If you liked, you could convert those findings into a PR for us (thanks for working out what they are!). I would imagine we would create a new Hint class for HSQLDB (in the configuration project, in the org.hsqldb package). Within that hints object encode your findings from above (follow the pattern in the surrounding hints to see how to capture that info), then add a small sample project for the samples folder, submit it with the hint and we'd be good to go?

**Comment by Query-Interface** [comment]
Hi,
OK, I will try. But I cannot work on this currently. I have some commitments at work. I should be able to start in 10 days.

**Comment by Query-Interface** [comment]
Hi,

Progress status: I have written the new Hint class and updated pet-clinic jpa to support hsqldb. I have a last runtime issue with the class **org.hsqldb.lib.FrameworkLogger** which is looking for the java.home properties to reconfigure the logging manager (see [https://sourceforge.net/p/hsqldb/src/org/hsqldb/lib/FrameworkLogger.java#l364](https://sourceforge.net/p/hsqldb/svn/HEAD/tree/base/trunk/src/org/hsqldb/lib/FrameworkLogger.java#l364)).

I guess I have to add a substitute class to fix that.

Regards

**Comment by Query-Interface** [comment]
Hi,
I have sent the PR: https://github.com/spring-projects-experimental/spring-graalvm-native/pull/395

Regards,
Arnaud

**Comment by devMls** [comment]
> We have h2 working with the petclinic. It might help people to get started if hsqldb worked as well.

Hi i am looking for a H2 graalvm compatible, do you achieve this?

**Comment by dsyer** [comment]
Yes. Isn't that what this means: "We have h2 working with the petclinic"?

**Comment by devMls** [comment]
ok, but i understand that you only work h2 in test before compile to graalvm. In other case, do you have a way to compile H2 with graalvm? the official repository don't support that, and it could be a good improvement

**Comment by dsyer** [comment]
I think you might be wrong. The petclinic works with h2 at runtime by default.

**Comment by devMls** [comment]
then i don't understand this issue:

https://github.com/h2database/h2database/issues/2207

I have a similar issue when i try to compile h2 embed in my app:

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readDouble(Bits.java:184)
Call path from entry point to org.h2.util.Bits.readDouble(byte[], int):
        at org.h2.util.Bits.readDouble(Bits.java:184)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readDoubleLE(Bits.java:198)
Call path from entry point to org.h2.util.Bits.readDoubleLE(byte[], int):
        at org.h2.util.Bits.readDoubleLE(Bits.java:198)
       at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readInt(Bits.java:128)
Call path from entry point to org.h2.util.Bits.readInt(byte[], int):
        at org.h2.util.Bits.readInt(Bits.java:128)
        at org.h2.security.AES.encryptBlock(AES.java:143)
        at org.h2.security.AES.encrypt(AES.java:127)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:68)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readIntLE(Bits.java:142)
Call path from entry point to org.h2.util.Bits.readIntLE(byte[], int):
        at org.h2.util.Bits.readIntLE(Bits.java:142)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readInt(EWKBUtils.java:206)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:396)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readLong(Bits.java:156)
Call path from entry point to org.h2.util.Bits.readLong(byte[], int):
        at org.h2.util.Bits.readLong(Bits.java:156)
        at org.h2.value.Value.convertToLong(Value.java:958)
        at org.h2.value.Value.convertTo(Value.java:766)
        at org.h2.value.Value.convertTo(Value.java:723)
        at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:565)
        at com.oracle.svm.reflect.PreparedStatement_setObject_5b494a5a8f7fcd76e8cd88a6cab852968d728fd3_3170.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.uuidToBytes(Bits.java:212)
Call path from entry point to org.h2.util.Bits.uuidToBytes(long, long):
        at org.h2.util.Bits.uuidToBytes(Bits.java:211)
        at org.h2.value.ValueUuid.getBytes(ValueUuid.java:201)
        at org.h2.jdbc.JdbcResultSet.getBytes(JdbcResultSet.java:1072)
        at org.h2.store.LobStorageBackend.readBlock(LobStorageBackend.java:232)
        at org.h2.store.LobStorageBackend$LobInputStream.fillBuffer(LobStorageBackend.java:770)
        at org.h2.store.LobStorageBackend$LobInputStream.readFully(LobStorageBackend.java:743)
        at org.h2.store.LobStorageBackend$LobInputStream.read(LobStorageBackend.java:729)
        at com.jogamp.common.util.IOUtil$StreamMonitor.run(IOUtil.java:912)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeDouble(Bits.java:300)
Call path from entry point to org.h2.util.Bits.writeDouble(byte[], int, double):
        at org.h2.util.Bits.writeDouble(Bits.java:300)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.writeDouble(EWKBUtils.java:162)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.addCoordinate(EWKBUtils.java:146)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:718)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:608)
        at org.h2.value.ValueGeometry.get(ValueGeometry.java:117)
        at org.h2.value.Transfer.readValue(Transfer.java:771)
        at org.h2.server.TcpServerThread.setParameters(TcpServerThread.java:257)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:331)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:175)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeInt(Bits.java:240)
Call path from entry point to org.h2.util.Bits.writeInt(byte[], int, int):
        at org.h2.util.Bits.writeInt(Bits.java:240)
        at org.h2.store.Data.writeInt(Data.java:166)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:61)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeLong(Bits.java:270)
Call path from entry point to org.h2.util.Bits.writeLong(byte[], int, long):
        at org.h2.util.Bits.writeLong(Bits.java:270)
        at org.h2.security.SecureFileStore.xorInitVector(SecureFileStore.java:102)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:67)
        at org.h2.store.FileStoreOutputStream.w

**Comment by dsyer** [comment]
I guess your app is using different features of h2 than the petclinic. It's great if the h2 dev team can do something there (much better for third party libraries to have support from their authors), so thanks for the link.

**Comment by devMls** [comment]
thanks for your pacience :)

**Comment by dsyer** [comment]
Feel free to open a new issue. Especially if you have a simple project that reproduces the error. We don't like fixing 3rd party libraries, but sometimes we can do it cheaply.

**Comment by ctoabidmaqbool** [comment]
Create a similar project which is using HSQLDb 2.6.0 and GraalVm with gluonfx-mobile-plugin (Javafx & Maven project).
https://github.com/ctoabidmaqbool/HSQLDb-On-GraalVM-NativeImage-Test.git

On Android HSQLDb database is not creating but on Dekstop working fine, I am unsure what is causing problem in Android.
