### ISSUE TITLE
Supporting reactor/webflux return types

### ISSUE THREAD

**Issue by hakandilek** [spring-projects-experimental/spring-graalvm-native#310]
Hello there,

First thank y'all for this great work on _almost_ uncharted waters. :slightly_smiling_face: 

I'have been playing around with the [webflux-netty sample](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/webflux-netty) and added this `GET /hello` endpoint to the existing `Foo` controller:
```
  @RestController
  class Foo {
...
    @GetMapping("/hello")
    public Mono<String> hello() {
      return Mono.just("World");
    }
  }
```
It runs and returns the value "World" on JVM as expected but but the native run fails to serialize `reactor.core.publisher.MonoJust` with the message:

```
...
2020-09-27 23:03:02.120  INFO 67895 --- [           main] com.example.webflux.WebfluxApplication   : Started WebfluxApplication in 0.046 seconds (JVM running for 0.048)
Sep 27, 2020 11:03:07 PM com.fasterxml.jackson.databind.ext.Java7Handlers <clinit>
WARNING: Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added
2020-09-27 23:03:07.907 ERROR 67895 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [74dc8013-1]  500 Server Error for HTTP GET "/hello"

org.springframework.core.codec.CodecException: Type definition error: [simple type, class reactor.core.publisher.MonoJust]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class reactor.core.publisher.MonoJust and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:176) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class reactor.core.publisher.MonoJust and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1277) ~[na:na]
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400) ~[na:na]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71) ~[na:na]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33) ~[na:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[na:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[na:na]
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516) ~[na:na]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006) ~[na:na]
	at org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:172) ~[na:na]
...
```

**Comment by aclement** [comment]
I added your endpoint to that sample and it seems to be working with a couple of fixes.

**Comment by hakandilek** [comment]
This is great. Thanks.
