### ISSUE TITLE
Dig into why spring-batch sample needs the wierd extra resource file

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-graalvm-native#314]
In the batch hints there is an unusual entry related to a properties file containing devtools references. It's presence/absence seems to influence spring batch behaviour.

**Comment by aclement** [comment]
Getting somewhere with this.  If this is missing from the resource patterns `META-INF/spring-autoconfigure-metadata.properties` then the native-image built batch sample fails with:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86) ~[na:na]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:68) ~[na:na]
	at org.springframework.util.SerializationUtils.serialize(SerializationUtils.java:47) ~[na:na]
```

So something about it's presence is triggering a different pattern of configuration resolution, presumably we are missing some other bit of `reflect-config.json`.  So I rebuilt the batch jar with that file deleted. It still runs fine (as it should, that file is an optimization). Then I re-ran that with the agent to collect a different set of configuration data. Then I rebuilt the native-image from the original (unmodified jar) without that pattern in (because the agent didn't collect it being accessed because it wasn't around). This time the native-image worked. So we can simply diff the two collected configurations via the agent and deduce what is different.

**Comment by aclement** [comment]
Solved.
The reason for it is the AutoConfigureAfter references. The sam.properties file captures the AutoConfigureAfter relationships amongst configurations.  Without that we make a mistake in that there is a chain of configurations marked autoconfiguration but although reflective access is granted to all the configs in the chain, because the middle one fails condition checks and is inactive, the class file for the configuration is not added to the image as a resource for that middle configuration. Without the resource Spring can’t dig through the class file and doesn’t see the AutoConfigureAfter in the middle and the chain is broken. We end up not running them all in the right order. In our case the chain seems to be:

```
@AutoConfigureAfter(HibernateJpaAutoConfiguration.class)
public class BatchAutoConfiguration {
```

```
@AutoConfigureAfter({ DataSourceAutoConfiguration.class })
public class HibernateJpaAutoConfiguration {
```

```
public class DataSourceAutoConfiguration {
```

And if HibernateJpaAutoConfiguration is not added as a .class resource, we don’t realize we have to run DataSourceAutoConfiguration first. The solution is to recognize for these referenced 'unnecessary configs', make sure if they have their own `@AutoConfigureBeforeAfter` on them, we add them as resource entries. A longer term play would be to generate a spring-autoconfigure-metadata.properties on the fly.
