### ISSUE TITLE
Add scheduling support

### ISSUE THREAD

**Issue by christian-draeger** [spring-projects-experimental/spring-graalvm-native#383]
My native-image generation is crashing when using schedulers on my servlet application.
When i remove `@EnableScheduling` from my application class the error goes away.
Since I could find nothing about scheduling in the sample projects i assume it's a bug or not supported for now?

here is my stacktrace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpointGroupsBeanPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: Invalid declaration of container type [org.springframework.scheduling.annotation.Schedules] for repeatable annotation [org.springframework.scheduling.annotation.Scheduled]; nested exception is java.lang.NoSuchMethodException: No value method found
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:526) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:244) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:767) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:572) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[na:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[na:na]
        at com.mhp.dv.dashboard.DashboardApplicationKt.main(DashboardApplication.kt:15) ~[na:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: Invalid declaration of container type [org.springframework.scheduling.annotation.Schedules] for repeatable annotation [org.springframework.scheduling.annotation.Scheduled]; nested exception is java.lang.NoSuchMethodException: No value method found
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:617) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[na:na]
        at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91) ~[na:na]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111) ~[backend:5.3.1]
        at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92) ~[backend:5.3.1]
        at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101) ~[backend:5.3.1]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251) ~[backend:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1144) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1119) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[na:na]
        ... 15 common frames omitted
Caused by: org.springframework.core.annotation.AnnotationConfigurationException: Invalid declaration of container type [org.springframework.scheduling.annotation.Schedules] for repeatable annotation [org.springframework.scheduling.annotation.Scheduled]; nested exception is java.lang.NoSuchMethodException: No value method found
        at org.springframework.core.annotation.RepeatableContainers$ExplicitRepeatableContainer.<init>(RepeatableContainers.java:219) ~[na:na]
        at org.springframework.core.annotation.RepeatableContainers.of(RepeatableContainers.java:117) ~[na:na]
        at org.springframework.core.annotation.AnnotatedElementUtils.getRepeatableAnnotations(AnnotatedElementUtils.java:759) ~[na:na]
```

are there any workarounds how i could make this thing work?

**Comment by aclement** [comment]
Whilst waiting for proper support for scheduling, this works:

I just used the agent to collect config and my scheduling sample went fine. Here is what I did:

1. I used the spring guide for scheduling https://spring.io/guides/gs/scheduling-tasks/ - cloning the repo https://github.com/spring-guides/gs-scheduling-tasks

2. Using the 'complete' sub folder as my sample I updated it to Boot 2.4.0 and added a dependency:
```
        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-graalvm-native</artifactId>
            <version>0.9.0-SNAPSHOT</version>
        </dependency>
```

3. Created a folder to hold config: `mkdir -p src/main/resources/META-INF/native-image`

4. Ran the sample with the agent to collect config: ` java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/scheduling-tasks-0.0.1-SNAPSHOT.jar`

5. Copied the compile.sh script from the commandlinerunner sample into here, updated the initial vars for this sample.

6. Ran the compile.sh script - it tripped over some entries in reflect-config.json and jni-config.json - I deleted those entries from the json files.

7. Ran the compile.sh again, it worked.

8. Ran the result:
```
2020-11-30 17:36:55.532  INFO 29839 --- [           main] c.e.s.SchedulingTasksApplication         : Started SchedulingTasksApplication in 0.03 seconds (JVM running for 0.031)
```

and my scheduled entries then started coming out on the log.

**Comment by aclement** [comment]
I converted the agent collected config computed above into hints and pushed the sample into our samples folder. Will it work for every scheduling scenario? Unlikely but that sample is working right now that at least means something works.
