### ISSUE TITLE
The actuator-webflux sample fails when adding the property management.server.port

### ISSUE THREAD

**Issue by magnus-larsson** [spring-projects-experimental/spring-graalvm-native#393]
# Summary

**spring-graalvm-native version: 0.8.3**

I have tried to separate the port used by the actuator from the standard http port using the property `management.server.port`.
The native compiled Spring Boot app fails to start up. I guess the most important error message in the log ouput is:

```
Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found
```

**Note:** Using the property `server.port` to set the http port works fine.

# Steps to reproduce the error

First, get the code and verify that the actuator-webflux - sample works out of the box:
(the `curl` command below is expected to return `UP`)

```
git clone git@github.com:spring-projects-experimental/spring-graalvm-native.git
cd spring-graalvm-native/spring-graalvm-native-samples/actuator-webflux
git checkout 0.8.3

../../mvnw spring-boot:build-image
docker-compose up -d
curl localhost:8080/actuator/health -s | jq -r .status
docker-compose down
```

Verify that using the property `server.port` to direct http traffic to port `7001` works fine:

```
echo "server.port=7001"  | tee -a src/main/resources/application.properties
../../mvnw spring-boot:build-image
printf "\n      - \"7001:7001\""  | tee -a docker-compose.yml
docker-compose up -d
curl localhost:7001/actuator/health -s | jq -r .status
docker-compose down
```

Try to separate the traffic to the actuator to port `4004` using the property `management.server.port` will fail:

```
echo "management.server.port=4004"  | tee -a src/main/resources/application.properties
../../mvnw spring-boot:build-image
printf "\n      - \"4004:4004\""  | tee -a docker-compose.yml
docker-compose up -d
```

The startup will fail!
The following error message can be found in the log output using the command: `docker-compose logs`: 

```
Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found
```

See below for the full log output.
 
Remove the stopped container:

```
docker-compose down
```

Verify that the property `management.server.port` works as expected without the native compiler:

```
java -jar target/actuator-webflux-0.0.1-SNAPSHOT.jar 
curl localhost:4004/actuator/health -s | jq -r .status
```

Expect log output similar to:

```
2020-12-01 07:38:01.217  INFO 24050 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 7001
2020-12-01 07:38:01.289  INFO 24050 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2020-12-01 07:38:01.337  INFO 24050 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 4004
2020-12-01 07:38:01.355  INFO 24050 --- [           main] c.example.actuator.ActuatorApplication   : Started ActuatorApplication in 2.631 seconds (JVM running for 3.186)
```

# Full log output of the failed startup

```
actuator-webflux_1  |
actuator-webflux_1  |   .   ____          _            __ _ _
actuator-webflux_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
actuator-webflux_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
actuator-webflux_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
actuator-webflux_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
actuator-webflux_1  |  =========|_|==============|___/=/_/_/_/
actuator-webflux_1  |  :: Spring Boot ::                (v2.4.0)
actuator-webflux_1  |
actuator-webflux_1  | 2020-12-01 06:56:56.618  INFO 1 --- [           main] c.example.actuator.ActuatorApplication   : Starting ActuatorApplication using Java 1.8.0_272 on 74fe52a0f488 with PID 1 (/workspace/com.example.actuator.ActuatorApplication started by cnb in /workspace)
actuator-webflux_1  | 2020-12-01 06:56:56.618  INFO 1 --- [           main] c.example.actuator.ActuatorApplication   : No active profile set, falling back to default profiles: default
actuator-webflux_1  | 2020-12-01 06:56:56.715  WARN 1 --- [           main] i.m.c.i.binder.jvm.JvmGcMetrics          : GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
actuator-webflux_1  | 2020-12-01 06:56:56.735  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 7001
actuator-webflux_1  | 2020-12-01 06:56:56.744  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableChildManagementContextConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 2020-12-01 06:56:56.745  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableChildManagementContextConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 2020-12-01 06:56:58.753  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
actuator-webflux_1  |
actuator-webflux_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
actuator-webflux_1  | 2020-12-01 06:56:58.755 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
actuator-webflux_1  |
actuator-webflux_1  | org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableChildManagementContextConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[com.example.actuator.ActuatorApplication:5.3.1]
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[com.example.actuator.ActuatorApplication:5.3.1]
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[na:na]
actuator-webflux_1  | 	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[com.example.actuator.ActuatorApplication:5.3.1]
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[com.example.actuator.ActuatorApplication:5.3.1]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:942) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at com.example.actuator.ActuatorApplication.main(ActuatorApplication.java:10) [com.example.actuator.ActuatorApplication:na]
actuator-webflux_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableChildManagementContextConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1318) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1216) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration.onApplicationEvent(ManagementContextAutoConfiguration.java:149) ~[com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration.onApplicationEvent(ManagementContextAutoConfiguration.java:121) ~[com.example.actuator.ActuatorApplication:2.4.0]
actuator-webflux_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:161) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:56) ~[na:na]
actuator-webflux_1  | 	at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40) ~[na:na]
actuator-webflux_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[com.example.actuator.ActuatorApplication:5.3.1]
actuator-webflux_1  | 	... 15 common frames omitted
actuator-webflux_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1310) ~[na:na]
actuator-webflux_1  | 	... 36 common frames omitted
actuator-webflux_1  | Caused by: java.lang.NoSuchMethodException: org.springframework.boot.actuate.autoconfigure.web.server.EnableChildManagementContextConfiguration.<init>()
actuator-webflux_1  | 	at java.lang.Class.getConstructor0(DynamicHub.java:3082) ~[na:na]
actuator-webflux_1  | 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178) ~[na:na]
actuator-webflux_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[na:na]
actuator-webflux_1  | 	... 37 common frames omitted
actuator-webflux_1  |
actuator-webflux_actuator-webflux_1 exited with code 1
```

**Comment by aclement** [comment]
Fixed - added hint for missing element. Unusual to need to add one for something ending `...Configuration` but it is introduced programmatically during event handling rather than discoverable purely statically from looking at annotations.

**Comment by magnus-larsson** [comment]
Great, thanks!

Just want to confirm that after switching to the master branch and then rebuilding the native Docker image it simply worked!
