### ISSUE TITLE
The data-mongodb-reactive sample fails when MongoDB requires authentication

### ISSUE THREAD

**Issue by magnus-larsson** [spring-projects-experimental/spring-graalvm-native#396]
# Summary

**spring-graalvm-native version: 0.8.3**

I have tried to use username and password to authenticate the data-mongodb-reactive sample app.   
It works when running the app as a normal jar-file but the native compiled Spring Boot app fails to start up.

Error message:

```
Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
```

See below for the full log output.

# Steps to reproduce the error

1. Get the code:

    ```
    git clone git@github.com:spring-projects-experimental/spring-graalvm-native.git
    cd spring-graalvm-native/spring-graalvm-native-samples/data-mongodb-reactive
    git checkout 0.8.3
    ```

2. Create a new `docker-compose-yml`:

    ```
    cat <<'EOF' >> docker-compose.yml
    version: '3.1'
    services:

      mongo-app:
        image: data-mongodb-reactive:0.0.1-SNAPSHOT
        environment:
          - SPRING_DATA_MONGODB_HOST=mongo
          - SPRING_DATA_MONGODB_PORT=27017
    #      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
    #      - SPRING_DATA_MONGODB_USERNAME=p
    #      - SPRING_DATA_MONGODB_PASSWORD=p
        depends_on:
          mongo:
            condition: service_healthy

      mongo:
        image: mongo:4.2
        ports:
          - 27017:27017
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=u
    #      - MONGO_INITDB_ROOT_PASSWORD=p
        healthcheck:
          test: "mongo --eval 'db.stats().ok'"
          interval: 20s
          timeout: 5s
          retries: 10
    EOF
    ```

3. Build the native Docker image and verify that it works without MongoDB credentials:

    ```
    ./mvnw spring-boot:build-image
    docker-compose up
    # A lot of output from MongoDB tests in the log output...
    CTRL/C
    docker-compose down
    ```

4. Remove the comments in `docker-compose.yml` to make MongoDB require credentials and the Spring Boot app to use credentials.

5. Test the native Docker image with MongoDB credentials:

    ```
    docker-compose up
    # Errors...
    ```

    See below for the full log output.

6. Verify that the Spring Boot app works using MongoDB credentials when not natively compiled:  
Start it in a separate terminal window and verify that het expected output is printed in the log:

    ```
    SPRING_DATA_MONGODB_HOST=localhost \
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin \
    SPRING_DATA_MONGODB_USERNAME=u \
    SPRING_DATA_MONGODB_PASSWORD=p \
    java -jar target/data-mongodb-reactive-0.0.1-SNAPSHOT.jar 
    # A lot of output from MongoDB tests in the log output...
    CTRL/C
    ```

7. Stop the containers:

    ```
    docker-compose down
    ```

# Full log output of the failed startup

```
mongo-app_1  |
mongo-app_1  |   .   ____          _            __ _ _
mongo-app_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
mongo-app_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
mongo-app_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
mongo-app_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
mongo-app_1  |  =========|_|==============|___/=/_/_/_/
mongo-app_1  |  :: Spring Boot ::
mongo-app_1  |
mongo-app_1  | 2020-12-02 07:07:33.063  INFO 1 --- [           main] com.example.data.mongo.MongoApplication  : Starting MongoApplication using Java 1.8.0_272 on b0f4bad36a35 with PID 1 (/workspace/com.example.data.mongo.MongoApplication started by cnb in /workspace)
mongo-app_1  | 2020-12-02 07:07:33.063  INFO 1 --- [           main] com.example.data.mongo.MongoApplication  : No active profile set, falling back to default profiles: default
mongo-app_1  | 2020-12-02 07:07:33.082  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive MongoDB repositories in DEFAULT mode.
mongo-app_1  | 2020-12-02 07:07:33.083  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1 ms. Found 1 Reactive MongoDB repository interfaces.
mongo-app_1  | 2020-12-02 07:07:33.084  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
mongo-app_1  | 2020-12-02 07:07:33.084  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 0 ms. Found 0 MongoDB repository interfaces.
mongo-app_1  | 2020-12-02 07:07:33.092  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
mongo-app_1  | 2020-12-02 07:07:33.093  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
mongo-app_1  | 2020-12-02 07:07:33.097  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:2}] to mongo:27017
mongo-app_1  | 2020-12-02 07:07:33.098  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1718600}
mongo-app_1  | 2020-12-02 07:07:33.101  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:4}] to mongo:27017
mongo-app_1  | 2020-12-02 07:07:33.101  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=4271200}
mongo-app_1  | 2020-12-02 07:07:33.101  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:4, serverValue:3}] to mongo:27017
mongo-app_1  | 2020-12-02 07:07:33.103  INFO 1 --- [l'}-mongo:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:5}] to mongo:27017
mongo-app_1  | 2020-12-02 07:07:33.120  INFO 1 --- [           main] tionInformation$PropertyDescriptorSource : Couldn't read class metadata for interface com.example.data.mongo.OrderProjection. Input property calculation might fail!
mongo-app_1  | 2020-12-02 07:07:33.130  INFO 1 --- [           main] org.mongodb.driver.connection            : Closed connection [connectionId{localValue:6}] to mongo:27017 because there was a socket exception raised by this connection.
mongo-app_1  | 2020-12-02 07:07:33.130  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
mongo-app_1  | 2020-12-02 07:07:33.131  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
mongo-app_1  |
mongo-app_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
mongo-app_1  | 2020-12-02 07:07:33.133 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
mongo-app_1  |
mongo-app_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
mongo-app_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
mongo-app_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[na:na]
mongo-app_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[na:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | 	at com.example.data.mongo.MongoApplication.main(MongoApplication.java:25) [com.example.data.mongo.MongoApplication:na]
mongo-app_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
mongo-app_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[na:na]
mongo-app_1  | 	... 19 common frames omitted
mongo-app_1  | Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
mongo-app_1  | 	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:133) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2882) ~[com.example.data.mongo.MongoApplication:3.1.1]
mongo-app_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:564) ~[com.example.data.mongo.MongoApplication:3.1.1]
mongo-app_1  | 	at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:214) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:156) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:146) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:130) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.<init>(MongoPersistentEntityIndexCreator.java:95) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.<init>(MongoPersistentEntityIndexCreator.java:72) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.<init>(MongoTemplate.java:250) ~[com.example.data.mongo.MongoApplication:3.1.1]
mongo-app_1  | 	at org.springframework.boot.autoconfigure.data.mongo.MongoDatabaseFactoryDependentConfiguration.mongoTemplate(MongoDatabaseFactoryDependentConfiguration.java:63) ~[com.example.data.mongo.MongoApplication:2.4.0]
mongo-app_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
mongo-app_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[na:na]
mongo-app_1  | 	... 20 common frames omitted
mongo-app_1  | Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='p', source='admin', password=<hidden>, mechanismProperties=<hidden>}
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:235) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:130) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.access$100(SaslAuthenticator.java:43) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:57) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:51) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:241) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:51) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:53) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticate(InternalStreamConnectionInitializer.java:168) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:63) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:144) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:51) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:431) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:115) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:100) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:92) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:119) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.ClientSessionBinding$SessionBindingConnectionSource.getConnection(ClientSessionBinding.java:135) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.operation.OperationHelper.withConnectionSource(OperationHelper.java:647) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.operation.OperationHelper.withConnection(OperationHelper.java:611) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:192) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:72) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:195) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825) ~[na:na]
mongo-app_1  | 	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.DefaultIndexOperations.lambda$ensureIndex$0(DefaultIndexOperations.java:131) ~[na:na]
mongo-app_1  | 	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:562) ~[com.example.data.mongo.MongoApplication:3.1.1]
mongo-app_1  | 	... 31 common frames omitted
mongo-app_1  | Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server mongo:27017. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
mongo-app_1  | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:359) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:280) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:191) ~[na:na]
mongo-app_1  | 	at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:128) ~[na:na]
mongo-app_1  | 	... 58 common frames omitted
mongo-app_1  |
```

**Comment by sdeleuze** [comment]
Could you please try to add `--enable-all-security-services` to `native-image` arguments to see if that fixes this issue?

**Comment by magnus-larsson** [comment]
Yes, it did! Thanks a lot for helping out!

II also had to fix my own typo in `docker-compose-yml`, where I set the username for the mongo-app to `p` instead of `u` :-)
