### ISSUE TITLE
com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()

### ISSUE THREAD

**Issue by String123** [spring-projects-experimental/spring-graalvm-native#414]
java.lang.ExceptionInInitializerError: null
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291) ~[na:na]
        at org.springframework.data.redis.cache.RedisCacheManager.createRedisCache(RedisCacheManager.java:278) ~[data-redis:2.4.2]
        at org.springframework.data.redis.cache.RedisCacheManager.getMissingCache(RedisCacheManager.java:251) ~[data-redis:2.4.2]
        at org.springframework.data.redis.cache.RedisCacheManager.getMissingCache(RedisCacheManager.java:48) ~[data-redis:2.4.2]
        at org.springframework.cache.support.AbstractCacheManager.getCache(AbstractCacheManager.java:97) ~[na:na]
        at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:89) ~[na:na]
        at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:252) ~[data-redis:5.3.2]
        at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.<init>(CacheAspectSupport.java:724) ~[na:na]
        at org.springframework.cache.interceptor.CacheAspectSupport.getOperationContext(CacheAspectSupport.java:265) ~[data-redis:5.3.2]
        at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts.<init>(CacheAspectSupport.java:615) ~[na:na]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[data-redis:5.3.2]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[na:na]
        at com.sun.proxy.$Proxy248.findByLastname(Unknown Source) ~[na:na]
        at com.example.data.redis.CLR.run(CLR.java:81) ~[data-redis:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[data-redis:2.4.1]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[data-redis:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[data-redis:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[data-redis:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[data-redis:2.4.1]
        at com.example.data.redis.RedisApplication.main(RedisApplication.java:25) ~[data-redis:na]
Caused by: org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:96) ~[na:na]
        at org.springframework.data.redis.cache.RedisCache.<clinit>(RedisCache.java:53) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271) ~[na:na]
        ... 21 common frames omitted
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:64) ~[na:na]
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33) ~[na:na]
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:94) ~[na:na]
        ... 24 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87) ~[na:na]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:68) ~[na:na]
        at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46) ~[na:na]
        at org.springframework.core.serializer.Serializer.serializeToByteArray(Serializer.java:56) ~[na:na]
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:60) ~[na:na]
        ... 26 common frames omitted

**Comment by String123** [comment]
https://github.com/String123/spring-graalvm-redis-test

**Comment by bclozel** [comment]
Hello @String123 

This is the expected behavior with GraalVM, [since Java serialization is not supported in that environment](https://www.graalvm.org/reference-manual/native-image/Limitations/#serialization).

You can fix that by configuring your redis cache to use a Jackson JSON serializer instead (or any other serializer that doesn't rely on Java serialization).

Thanks!
