### ISSUE TITLE
UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed

### ISSUE THREAD

**Issue by MarioMO98** [spring-projects-experimental/spring-graalvm-native#435]
Greetings,

we are getting problems compiling one of your samples in Windows 10 (https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/cloud-function-netty).

We have followed the instructions detailed in the official documentation for GraalVM on Windows and we are using GraalVM v 20.3 for Java 8, and Spring GraalVM Native 0.9.0.

In first instance, we had to add the native profile to the sample's pom.xml (https://github.com/spring-projects-experimental/spring-graalvm-native/issues/233#issuecomment-675248536) but, in our case, we changed the main class to the sample main class (com.example.demo.DemoApplication), and execute the mvn -pNative clean package.

Then, we activate the sdk-7.1 environment in a command shell because we got an error that says we have not installed SDK 7.1 (which is not true) running this command: call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd".

Now, it seems the compilation continues, but we are getting **com.oracle.graal.pointsto.constraints.UnsupportedFeatureException**:

_Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.nio.ch.Iocp.
Detailed message:
Trace:
        at parsing sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(WindowsAsynchronousFileChannelImpl.java:105)
Call path from entry point to sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(FileDescriptor, boolean, boolean, ThreadPool):
        at sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(WindowsAsynchronousFileChannelImpl.java:104)
        at sun.nio.fs.WindowsChannelFactory.newAsynchronousFileChannel(WindowsChannelFactory.java:208)
        at sun.nio.fs.WindowsFileSystemProvider.newAsynchronousFileChannel(WindowsFileSystemProvider.java:140)
        at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248)
        at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:301)
        at org.springframework.core.io.buffer.DataBufferUtils.lambda$read$6(DataBufferUtils.java:224)
        at org.springframework.core.io.buffer.DataBufferUtils$$Lambda$1113/1779033696.call(Unknown Source)
        at reactor.core.publisher.MonoCallable.block(MonoCallable.java:81)
        at reactor.core.publisher.MonoCallable.block(MonoCallable.java:74)
        at org.springframework.boot.web.embedded.netty.NettyWebServer$1.run(NettyWebServer.java:160)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)_

How could we resolve this error?

Thanks in advance, 

Cheers.

**Comment by sdeleuze** [comment]
Since it seems plaform specific, I would suggest to raise this issue on https://github.com/oracle/graal/issues side with a simple repro invoking `AsynchronousFileChannel.open(file.toPath(), StandardOpenOption.READ)`.
