### ISSUE TITLE
Add actuator support

### ISSUE THREAD

**Issue by mbagliojr** [spring-projects-experimental/spring-graalvm-native#9]
I'm seeing the error below when trying to use the command line runner example.

No @CompilationHint found for import selector: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextConfigurationImportSelector

What is the best way to determine the root cause of an error during native-image?

**Comment by aclement** [comment]
Many errors are very confusing. And currently if you stray much beyond the existing usage demonstrated in samples, it will start failing (it is still pre 1.0).

That said, if you ever get a 'class not found' type message you can quickly try to fix that yourself by creating your own reflect-config.json file in the project META-INF/native-image folder, per the instructions in https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md.

However, in this case the feature is trying to tell you something early so we don't get a very cryptic error later. The features encapsulates hints on various types that suggest "oh if this type is being used, we need to make sure graal can reflect on these other types".  At the moment each selector needs specific handling that specifics what types it might select. We'll need to add handling for `ManagementContextConfigurationImportSelector`.

**Comment by sdeleuze** [comment]
This error happens when you add actuator support, so I turn it into a more general one.

**Comment by YanzheL** [comment]
Similar error happened in `spring-kafka-2.3.1-RELEASE`

```
Fatal error: java.lang.IllegalStateException: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.kafka.annotation.KafkaListenerConfigurationSelector
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:479)
```

**Comment by aclement** [comment]
There are now actuator samples in the repository so the feature does support basic usage of actuator - please try it out and let me know how it goes. 

> So this issue is not specific to spring-actuator, and it requires a more general solution.

The problem is difficult to solve in the general sense because import selectors can do anything they want in code to compute the result of calling them at runtime. It isn't reasonable to analyze the code to work it out, so we need a hint. The messages coming out now are warning there is no hint and failing early rather than more cryptically later. The docs discuss how to create a hint when you get the problem (and perhaps contribute it back):

https://repo.spring.io/milestone/org/springframework/experimental/spring-graal-native-docs/0.6.1.RELEASE/spring-graal-native-docs-0.6.1.RELEASE.zip!/reference/index.html#_no_access_hint_found_for_import_selector_xxx

Supporting actuator was writing a complicated hint. But as I was there I also dropped one in for the `KafkaListenerConfigurationSelector` - however there will be import selectors out in the wild that we have no idea about, and supplying hints with them (or turning this error down to warning if you want to risk it) is the current mechanism to support it.

Please reopen if actuator not behaving for you, I am pretty sure our two samples do not cover it exhaustively.
